// Generated by gen_regs.tcl
// DO NOT EDIT THIS FILE

#ifndef __LP_REGS_H__
#define __LP_REGS_H__

#ifdef __cplusplus
    extern "C" {
#endif

#include <stdint.h>
#include "chip_mem_layout.h"

////////////////////////////////////////////////////////////////
// baisc reg info                                             //
////////////////////////////////////////////////////////////////

#define LP_REG_RW_M3_STCALIB_ADDR            (LP_CFG_BASE+0x000)

#define LP_REG_RW_M3_AUXFAULT_ADDR           (LP_CFG_BASE+0x004)

#define LP_REG_RW_M3_MPUDISABLE_ADDR         (LP_CFG_BASE+0x008)

#define LP_REG_RO_M3_BRCHSTAT_ADDR           (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_BRCHSTAT_LSB            0
#define LP_REG_RO_M3_BRCHSTAT_MASK           0x0000000f

#define LP_REG_RO_M3_HALTED_ADDR             (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_HALTED_LSB              4
#define LP_REG_RO_M3_HALTED_MASK             0x00000010

#define LP_REG_RO_M3_LOCKUP_ADDR             (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_LOCKUP_LSB              5
#define LP_REG_RO_M3_LOCKUP_MASK             0x00000020

#define LP_REG_RO_M3_SLEEPDEEP_ADDR          (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_SLEEPDEEP_LSB           6
#define LP_REG_RO_M3_SLEEPDEEP_MASK          0x00000040

#define LP_REG_RO_M3_ETMINTNUM_ADDR          (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_ETMINTNUM_LSB           7
#define LP_REG_RO_M3_ETMINTNUM_MASK          0x0000ff80

#define LP_REG_RO_M3_ETMINTSTAT_ADDR         (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_ETMINTSTAT_LSB          16
#define LP_REG_RO_M3_ETMINTSTAT_MASK         0x00070000

#define LP_REG_RO_M3_CURRPRI_ADDR            (LP_CFG_BASE+0x00c)
#define LP_REG_RO_M3_CURRPRI_LSB             19
#define LP_REG_RO_M3_CURRPRI_MASK            0x07f80000

#define LP_REG_RO_M3_INTERNALSTATE_0_ADDR    (LP_CFG_BASE+0x010)
#define LP_REG_RO_M3_INTERNALSTATE_1_ADDR    (LP_CFG_BASE+0x014)
#define LP_REG_RO_M3_INTERNALSTATE_2_ADDR    (LP_CFG_BASE+0x018)
#define LP_REG_RO_M3_INTERNALSTATE_3_ADDR    (LP_CFG_BASE+0x01c)
#define LP_REG_RO_M3_INTERNALSTATE_4_ADDR    (LP_CFG_BASE+0x020)

#define LP_REG_RW_INTR_MASK_0_ADDR           (LP_CFG_BASE+0x030)
#define LP_REG_RW_INTR_MASK_1_ADDR           (LP_CFG_BASE+0x034)
#define LP_REG_RW_INTR_MASK_2_ADDR           (LP_CFG_BASE+0x038)
#define LP_REG_RW_INTR_MASK_3_ADDR           (LP_CFG_BASE+0x03c)

#define LP_REG_RW_WDT0_SPEED_UP_ADDR         (LP_CFG_BASE+0x040)

#define LP_REG_RW_LP_REMAP_ADDR              (LP_CFG_BASE+0x044)

#define LP_REG_RW_M3_CLK_EN_ADDR             (LP_CFG_BASE+0x100)

#define LP_REG_RW_DAP_CLK_EN_ADDR            (LP_CFG_BASE+0x104)

#define LP_REG_RW_DMAC0_CLK_EN_ADDR          (LP_CFG_BASE+0x108)

#define LP_REG_RW_BOOTROM0_CLK_EN_ADDR       (LP_CFG_BASE+0x10c)

#define LP_REG_RW_VAD_CFGCLK_EN_ADDR         (LP_CFG_BASE+0x110)
#define LP_REG_RW_VAD_CFGCLK_EN_LSB          0
#define LP_REG_RW_VAD_CFGCLK_EN_MASK         0x00000001

#define LP_REG_RW_VAD_CLK_EN_ADDR            (LP_CFG_BASE+0x110)
#define LP_REG_RW_VAD_CLK_EN_LSB             1
#define LP_REG_RW_VAD_CLK_EN_MASK            0x00000002

#define LP_REG_RW_UART0_CFGCLK_EN_ADDR       (LP_CFG_BASE+0x114)
#define LP_REG_RW_UART0_CFGCLK_EN_LSB        0
#define LP_REG_RW_UART0_CFGCLK_EN_MASK       0x00000001

#define LP_REG_RW_UART0_CLK_EN_ADDR          (LP_CFG_BASE+0x114)
#define LP_REG_RW_UART0_CLK_EN_LSB           1
#define LP_REG_RW_UART0_CLK_EN_MASK          0x00000002

#define LP_REG_RW_I2C0_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x118)
#define LP_REG_RW_I2C0_CFGCLK_EN_LSB         0
#define LP_REG_RW_I2C0_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_I2C0_CLK_EN_ADDR           (LP_CFG_BASE+0x118)
#define LP_REG_RW_I2C0_CLK_EN_LSB            1
#define LP_REG_RW_I2C0_CLK_EN_MASK           0x00000002

#define LP_REG_RW_TIMER0_CFGCLK_EN_ADDR      (LP_CFG_BASE+0x11c)

#define LP_REG_RW_I2S0_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x120)
#define LP_REG_RW_I2S0_CFGCLK_EN_LSB         0
#define LP_REG_RW_I2S0_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_I2S0_CLK_EN_ADDR           (LP_CFG_BASE+0x120)
#define LP_REG_RW_I2S0_CLK_EN_LSB            1
#define LP_REG_RW_I2S0_CLK_EN_MASK           0x00000002

#define LP_REG_RW_MAILBOX_CFGCLK_EN_ADDR     (LP_CFG_BASE+0x124)

#define LP_REG_RW_PDM0_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x128)
#define LP_REG_RW_PDM0_CFGCLK_EN_LSB         0
#define LP_REG_RW_PDM0_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_PDM0_CLK_EN_ADDR           (LP_CFG_BASE+0x128)
#define LP_REG_RW_PDM0_CLK_EN_LSB            1
#define LP_REG_RW_PDM0_CLK_EN_MASK           0x00000002

#define LP_REG_RW_PDM1_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x12c)
#define LP_REG_RW_PDM1_CFGCLK_EN_LSB         0
#define LP_REG_RW_PDM1_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_PDM1_CLK_EN_ADDR           (LP_CFG_BASE+0x12c)
#define LP_REG_RW_PDM1_CLK_EN_LSB            1
#define LP_REG_RW_PDM1_CLK_EN_MASK           0x00000002

#define LP_REG_RW_PDM2_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x130)
#define LP_REG_RW_PDM2_CFGCLK_EN_LSB         0
#define LP_REG_RW_PDM2_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_PDM2_CLK_EN_ADDR           (LP_CFG_BASE+0x130)
#define LP_REG_RW_PDM2_CLK_EN_LSB            1
#define LP_REG_RW_PDM2_CLK_EN_MASK           0x00000002

#define LP_REG_RW_PDM3_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x134)
#define LP_REG_RW_PDM3_CFGCLK_EN_LSB         0
#define LP_REG_RW_PDM3_CFGCLK_EN_MASK        0x00000001

#define LP_REG_RW_PDM3_CLK_EN_ADDR           (LP_CFG_BASE+0x134)
#define LP_REG_RW_PDM3_CLK_EN_LSB            1
#define LP_REG_RW_PDM3_CLK_EN_MASK           0x00000002

#define LP_REG_RW_WDT0_CFGCLK_EN_ADDR        (LP_CFG_BASE+0x138)

#define LP_REG_RW_PDM0_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x200)
#define LP_REG_RW_PDM0_DMA_HS_SEL_LSB        0
#define LP_REG_RW_PDM0_DMA_HS_SEL_MASK       0x00000007

#define LP_REG_RW_PDM1_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x200)
#define LP_REG_RW_PDM1_DMA_HS_SEL_LSB        8
#define LP_REG_RW_PDM1_DMA_HS_SEL_MASK       0x00000700

#define LP_REG_RW_PDM2_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x200)
#define LP_REG_RW_PDM2_DMA_HS_SEL_LSB        16
#define LP_REG_RW_PDM2_DMA_HS_SEL_MASK       0x00070000

#define LP_REG_RW_PDM3_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x200)
#define LP_REG_RW_PDM3_DMA_HS_SEL_LSB        24
#define LP_REG_RW_PDM3_DMA_HS_SEL_MASK       0x07000000

#define LP_REG_RW_I2S0_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x200)
#define LP_REG_RW_I2S0_DMA_HS_SEL_LSB        28
#define LP_REG_RW_I2S0_DMA_HS_SEL_MASK       0x70000000

#define LP_REG_RW_I2C0_DMA_HS_SEL_ADDR       (LP_CFG_BASE+0x204)
#define LP_REG_RW_I2C0_DMA_HS_SEL_LSB        0
#define LP_REG_RW_I2C0_DMA_HS_SEL_MASK       0x00000003

#define LP_REG_RW_VAD_DMA_HS_SEL_ADDR        (LP_CFG_BASE+0x204)
#define LP_REG_RW_VAD_DMA_HS_SEL_LSB         4
#define LP_REG_RW_VAD_DMA_HS_SEL_MASK        0x00000030

#define LP_REG_RW_UART0_DMA_HS_SEL_ADDR      (LP_CFG_BASE+0x204)
#define LP_REG_RW_UART0_DMA_HS_SEL_LSB       8
#define LP_REG_RW_UART0_DMA_HS_SEL_MASK      0x00000300

#define LP_REG_RW_IP_DMA_HS_SEL_0_ADDR       (LP_CFG_BASE+0x208)
#define LP_REG_RW_IP_DMA_HS_SEL_0_LSB        0
#define LP_REG_RW_IP_DMA_HS_SEL_0_MASK       0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_1_ADDR       (LP_CFG_BASE+0x208)
#define LP_REG_RW_IP_DMA_HS_SEL_1_LSB        16
#define LP_REG_RW_IP_DMA_HS_SEL_1_MASK       0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_2_ADDR       (LP_CFG_BASE+0x20c)
#define LP_REG_RW_IP_DMA_HS_SEL_2_LSB        0
#define LP_REG_RW_IP_DMA_HS_SEL_2_MASK       0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_3_ADDR       (LP_CFG_BASE+0x20c)
#define LP_REG_RW_IP_DMA_HS_SEL_3_LSB        16
#define LP_REG_RW_IP_DMA_HS_SEL_3_MASK       0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_4_ADDR       (LP_CFG_BASE+0x210)
#define LP_REG_RW_IP_DMA_HS_SEL_4_LSB        0
#define LP_REG_RW_IP_DMA_HS_SEL_4_MASK       0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_5_ADDR       (LP_CFG_BASE+0x210)
#define LP_REG_RW_IP_DMA_HS_SEL_5_LSB        16
#define LP_REG_RW_IP_DMA_HS_SEL_5_MASK       0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_6_ADDR       (LP_CFG_BASE+0x214)
#define LP_REG_RW_IP_DMA_HS_SEL_6_LSB        0
#define LP_REG_RW_IP_DMA_HS_SEL_6_MASK       0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_7_ADDR       (LP_CFG_BASE+0x214)
#define LP_REG_RW_IP_DMA_HS_SEL_7_LSB        16
#define LP_REG_RW_IP_DMA_HS_SEL_7_MASK       0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_8_ADDR       (LP_CFG_BASE+0x218)
#define LP_REG_RW_IP_DMA_HS_SEL_8_LSB        0
#define LP_REG_RW_IP_DMA_HS_SEL_8_MASK       0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_9_ADDR       (LP_CFG_BASE+0x218)
#define LP_REG_RW_IP_DMA_HS_SEL_9_LSB        16
#define LP_REG_RW_IP_DMA_HS_SEL_9_MASK       0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_10_ADDR      (LP_CFG_BASE+0x21c)
#define LP_REG_RW_IP_DMA_HS_SEL_10_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_10_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_11_ADDR      (LP_CFG_BASE+0x21c)
#define LP_REG_RW_IP_DMA_HS_SEL_11_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_11_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_12_ADDR      (LP_CFG_BASE+0x220)
#define LP_REG_RW_IP_DMA_HS_SEL_12_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_12_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_13_ADDR      (LP_CFG_BASE+0x220)
#define LP_REG_RW_IP_DMA_HS_SEL_13_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_13_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_14_ADDR      (LP_CFG_BASE+0x224)
#define LP_REG_RW_IP_DMA_HS_SEL_14_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_14_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_15_ADDR      (LP_CFG_BASE+0x224)
#define LP_REG_RW_IP_DMA_HS_SEL_15_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_15_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_16_ADDR      (LP_CFG_BASE+0x228)
#define LP_REG_RW_IP_DMA_HS_SEL_16_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_16_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_17_ADDR      (LP_CFG_BASE+0x228)
#define LP_REG_RW_IP_DMA_HS_SEL_17_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_17_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_18_ADDR      (LP_CFG_BASE+0x22c)
#define LP_REG_RW_IP_DMA_HS_SEL_18_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_18_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_19_ADDR      (LP_CFG_BASE+0x22c)
#define LP_REG_RW_IP_DMA_HS_SEL_19_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_19_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_20_ADDR      (LP_CFG_BASE+0x230)
#define LP_REG_RW_IP_DMA_HS_SEL_20_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_20_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_21_ADDR      (LP_CFG_BASE+0x230)
#define LP_REG_RW_IP_DMA_HS_SEL_21_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_21_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_22_ADDR      (LP_CFG_BASE+0x234)
#define LP_REG_RW_IP_DMA_HS_SEL_22_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_22_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_23_ADDR      (LP_CFG_BASE+0x234)
#define LP_REG_RW_IP_DMA_HS_SEL_23_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_23_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_24_ADDR      (LP_CFG_BASE+0x238)
#define LP_REG_RW_IP_DMA_HS_SEL_24_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_24_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_25_ADDR      (LP_CFG_BASE+0x238)
#define LP_REG_RW_IP_DMA_HS_SEL_25_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_25_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_26_ADDR      (LP_CFG_BASE+0x23c)
#define LP_REG_RW_IP_DMA_HS_SEL_26_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_26_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_27_ADDR      (LP_CFG_BASE+0x23c)
#define LP_REG_RW_IP_DMA_HS_SEL_27_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_27_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_28_ADDR      (LP_CFG_BASE+0x240)
#define LP_REG_RW_IP_DMA_HS_SEL_28_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_28_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_29_ADDR      (LP_CFG_BASE+0x240)
#define LP_REG_RW_IP_DMA_HS_SEL_29_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_29_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_30_ADDR      (LP_CFG_BASE+0x244)
#define LP_REG_RW_IP_DMA_HS_SEL_30_LSB       0
#define LP_REG_RW_IP_DMA_HS_SEL_30_MASK      0x0000ffff
#define LP_REG_RW_IP_DMA_HS_SEL_31_ADDR      (LP_CFG_BASE+0x244)
#define LP_REG_RW_IP_DMA_HS_SEL_31_LSB       16
#define LP_REG_RW_IP_DMA_HS_SEL_31_MASK      0xffff0000
#define LP_REG_RW_IP_DMA_HS_SEL_32_ADDR      (LP_CFG_BASE+0x248)

#define LP_REG_RW_ICACHE_EN_ADDR             (LP_CFG_BASE+0x300)

////////////////////////////////////////////////////////////////
// reg access                                                 //
////////////////////////////////////////////////////////////////
#define LP_REG32(name)                       (*(volatile uint32_t*)name##_ADDR)

#define LP_GET_REG_RW_M3_STCALIB             LP_REG32(LP_REG_RW_M3_STCALIB)
#define LP_SET_REG_RW_M3_STCALIB(x)          LP_REG32(LP_REG_RW_M3_STCALIB) = (uint32_t)(x)
#define LP_GET_REG_RW_M3_AUXFAULT            LP_REG32(LP_REG_RW_M3_AUXFAULT)
#define LP_SET_REG_RW_M3_AUXFAULT(x)         LP_REG32(LP_REG_RW_M3_AUXFAULT) = (uint32_t)(x)
#define LP_GET_REG_RW_M3_MPUDISABLE          LP_REG32(LP_REG_RW_M3_MPUDISABLE)
#define LP_SET_REG_RW_M3_MPUDISABLE(x)       LP_REG32(LP_REG_RW_M3_MPUDISABLE) = (uint32_t)(x)
#define LP_GET_REG_RO_M3_INTERNALSTATE_0     LP_REG32(LP_REG_RO_M3_INTERNALSTATE_0)
#define LP_GET_REG_RO_M3_INTERNALSTATE_1     LP_REG32(LP_REG_RO_M3_INTERNALSTATE_1)
#define LP_GET_REG_RO_M3_INTERNALSTATE_2     LP_REG32(LP_REG_RO_M3_INTERNALSTATE_2)
#define LP_GET_REG_RO_M3_INTERNALSTATE_3     LP_REG32(LP_REG_RO_M3_INTERNALSTATE_3)
#define LP_GET_REG_RO_M3_INTERNALSTATE_4     LP_REG32(LP_REG_RO_M3_INTERNALSTATE_4)
#define LP_GET_REG_RW_INTR_MASK_0            LP_REG32(LP_REG_RW_INTR_MASK_0)
#define LP_SET_REG_RW_INTR_MASK_0(x)         LP_REG32(LP_REG_RW_INTR_MASK_0) = (uint32_t)(x)
#define LP_GET_REG_RW_INTR_MASK_1            LP_REG32(LP_REG_RW_INTR_MASK_1)
#define LP_SET_REG_RW_INTR_MASK_1(x)         LP_REG32(LP_REG_RW_INTR_MASK_1) = (uint32_t)(x)
#define LP_GET_REG_RW_INTR_MASK_2            LP_REG32(LP_REG_RW_INTR_MASK_2)
#define LP_SET_REG_RW_INTR_MASK_2(x)         LP_REG32(LP_REG_RW_INTR_MASK_2) = (uint32_t)(x)
#define LP_GET_REG_RW_INTR_MASK_3            LP_REG32(LP_REG_RW_INTR_MASK_3)
#define LP_SET_REG_RW_INTR_MASK_3(x)         LP_REG32(LP_REG_RW_INTR_MASK_3) = (uint32_t)(x)
#define LP_GET_REG_RW_WDT0_SPEED_UP          LP_REG32(LP_REG_RW_WDT0_SPEED_UP)
#define LP_SET_REG_RW_WDT0_SPEED_UP(x)       LP_REG32(LP_REG_RW_WDT0_SPEED_UP) = (uint32_t)(x)
#define LP_GET_REG_RW_LP_REMAP               LP_REG32(LP_REG_RW_LP_REMAP)
#define LP_SET_REG_RW_LP_REMAP(x)            LP_REG32(LP_REG_RW_LP_REMAP) = (uint32_t)(x)
#define LP_GET_REG_RW_M3_CLK_EN              LP_REG32(LP_REG_RW_M3_CLK_EN)
#define LP_SET_REG_RW_M3_CLK_EN(x)           LP_REG32(LP_REG_RW_M3_CLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_DAP_CLK_EN             LP_REG32(LP_REG_RW_DAP_CLK_EN)
#define LP_SET_REG_RW_DAP_CLK_EN(x)          LP_REG32(LP_REG_RW_DAP_CLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_DMAC0_CLK_EN           LP_REG32(LP_REG_RW_DMAC0_CLK_EN)
#define LP_SET_REG_RW_DMAC0_CLK_EN(x)        LP_REG32(LP_REG_RW_DMAC0_CLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_BOOTROM0_CLK_EN        LP_REG32(LP_REG_RW_BOOTROM0_CLK_EN)
#define LP_SET_REG_RW_BOOTROM0_CLK_EN(x)     LP_REG32(LP_REG_RW_BOOTROM0_CLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_TIMER0_CFGCLK_EN       LP_REG32(LP_REG_RW_TIMER0_CFGCLK_EN)
#define LP_SET_REG_RW_TIMER0_CFGCLK_EN(x)    LP_REG32(LP_REG_RW_TIMER0_CFGCLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_MAILBOX_CFGCLK_EN      LP_REG32(LP_REG_RW_MAILBOX_CFGCLK_EN)
#define LP_SET_REG_RW_MAILBOX_CFGCLK_EN(x)   LP_REG32(LP_REG_RW_MAILBOX_CFGCLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_WDT0_CFGCLK_EN         LP_REG32(LP_REG_RW_WDT0_CFGCLK_EN)
#define LP_SET_REG_RW_WDT0_CFGCLK_EN(x)      LP_REG32(LP_REG_RW_WDT0_CFGCLK_EN) = (uint32_t)(x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_32       LP_REG32(LP_REG_RW_IP_DMA_HS_SEL_32)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_32(x)    LP_REG32(LP_REG_RW_IP_DMA_HS_SEL_32) = (uint32_t)(x)
#define LP_GET_REG_RW_ICACHE_EN              LP_REG32(LP_REG_RW_ICACHE_EN)
#define LP_SET_REG_RW_ICACHE_EN(x)           LP_REG32(LP_REG_RW_ICACHE_EN) = (uint32_t)(x)

////////////////////////////////////////////////////////////////
// reg bits access                                            //
////////////////////////////////////////////////////////////////
#define LP_GET_REG32_BITS(name)              ((LP_REG32(name) & name##_MASK) >> name##_LSB)
#define LP_SET_REG32_BITS(name,x)            do { \
    uint32_t val = LP_REG32(name); \
    val &= ~name##_MASK; \
    val |= ((x) << name##_LSB) & name##_MASK; \
    LP_REG32(name) = val; \
} while(0)

#define LP_GET_REG_RO_M3_BRCHSTAT            LP_GET_REG32_BITS(LP_REG_RO_M3_BRCHSTAT)
#define LP_GET_REG_RO_M3_HALTED              LP_GET_REG32_BITS(LP_REG_RO_M3_HALTED)
#define LP_GET_REG_RO_M3_LOCKUP              LP_GET_REG32_BITS(LP_REG_RO_M3_LOCKUP)
#define LP_GET_REG_RO_M3_SLEEPDEEP           LP_GET_REG32_BITS(LP_REG_RO_M3_SLEEPDEEP)
#define LP_GET_REG_RO_M3_ETMINTNUM           LP_GET_REG32_BITS(LP_REG_RO_M3_ETMINTNUM)
#define LP_GET_REG_RO_M3_ETMINTSTAT          LP_GET_REG32_BITS(LP_REG_RO_M3_ETMINTSTAT)
#define LP_GET_REG_RO_M3_CURRPRI             LP_GET_REG32_BITS(LP_REG_RO_M3_CURRPRI)
#define LP_GET_REG_RW_VAD_CFGCLK_EN          LP_GET_REG32_BITS(LP_REG_RW_VAD_CFGCLK_EN)
#define LP_SET_REG_RW_VAD_CFGCLK_EN(x)       LP_SET_REG32_BITS(LP_REG_RW_VAD_CFGCLK_EN,x)
#define LP_GET_REG_RW_VAD_CLK_EN             LP_GET_REG32_BITS(LP_REG_RW_VAD_CLK_EN)
#define LP_SET_REG_RW_VAD_CLK_EN(x)          LP_SET_REG32_BITS(LP_REG_RW_VAD_CLK_EN,x)
#define LP_GET_REG_RW_UART0_CFGCLK_EN        LP_GET_REG32_BITS(LP_REG_RW_UART0_CFGCLK_EN)
#define LP_SET_REG_RW_UART0_CFGCLK_EN(x)     LP_SET_REG32_BITS(LP_REG_RW_UART0_CFGCLK_EN,x)
#define LP_GET_REG_RW_UART0_CLK_EN           LP_GET_REG32_BITS(LP_REG_RW_UART0_CLK_EN)
#define LP_SET_REG_RW_UART0_CLK_EN(x)        LP_SET_REG32_BITS(LP_REG_RW_UART0_CLK_EN,x)
#define LP_GET_REG_RW_I2C0_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_I2C0_CFGCLK_EN)
#define LP_SET_REG_RW_I2C0_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_I2C0_CFGCLK_EN,x)
#define LP_GET_REG_RW_I2C0_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_I2C0_CLK_EN)
#define LP_SET_REG_RW_I2C0_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_I2C0_CLK_EN,x)
#define LP_GET_REG_RW_I2S0_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_I2S0_CFGCLK_EN)
#define LP_SET_REG_RW_I2S0_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_I2S0_CFGCLK_EN,x)
#define LP_GET_REG_RW_I2S0_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_I2S0_CLK_EN)
#define LP_SET_REG_RW_I2S0_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_I2S0_CLK_EN,x)
#define LP_GET_REG_RW_PDM0_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_PDM0_CFGCLK_EN)
#define LP_SET_REG_RW_PDM0_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_PDM0_CFGCLK_EN,x)
#define LP_GET_REG_RW_PDM0_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_PDM0_CLK_EN)
#define LP_SET_REG_RW_PDM0_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_PDM0_CLK_EN,x)
#define LP_GET_REG_RW_PDM1_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_PDM1_CFGCLK_EN)
#define LP_SET_REG_RW_PDM1_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_PDM1_CFGCLK_EN,x)
#define LP_GET_REG_RW_PDM1_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_PDM1_CLK_EN)
#define LP_SET_REG_RW_PDM1_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_PDM1_CLK_EN,x)
#define LP_GET_REG_RW_PDM2_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_PDM2_CFGCLK_EN)
#define LP_SET_REG_RW_PDM2_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_PDM2_CFGCLK_EN,x)
#define LP_GET_REG_RW_PDM2_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_PDM2_CLK_EN)
#define LP_SET_REG_RW_PDM2_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_PDM2_CLK_EN,x)
#define LP_GET_REG_RW_PDM3_CFGCLK_EN         LP_GET_REG32_BITS(LP_REG_RW_PDM3_CFGCLK_EN)
#define LP_SET_REG_RW_PDM3_CFGCLK_EN(x)      LP_SET_REG32_BITS(LP_REG_RW_PDM3_CFGCLK_EN,x)
#define LP_GET_REG_RW_PDM3_CLK_EN            LP_GET_REG32_BITS(LP_REG_RW_PDM3_CLK_EN)
#define LP_SET_REG_RW_PDM3_CLK_EN(x)         LP_SET_REG32_BITS(LP_REG_RW_PDM3_CLK_EN,x)
#define LP_GET_REG_RW_PDM0_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_PDM0_DMA_HS_SEL)
#define LP_SET_REG_RW_PDM0_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_PDM0_DMA_HS_SEL,x)
#define LP_GET_REG_RW_PDM1_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_PDM1_DMA_HS_SEL)
#define LP_SET_REG_RW_PDM1_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_PDM1_DMA_HS_SEL,x)
#define LP_GET_REG_RW_PDM2_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_PDM2_DMA_HS_SEL)
#define LP_SET_REG_RW_PDM2_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_PDM2_DMA_HS_SEL,x)
#define LP_GET_REG_RW_PDM3_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_PDM3_DMA_HS_SEL)
#define LP_SET_REG_RW_PDM3_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_PDM3_DMA_HS_SEL,x)
#define LP_GET_REG_RW_I2S0_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_I2S0_DMA_HS_SEL)
#define LP_SET_REG_RW_I2S0_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_I2S0_DMA_HS_SEL,x)
#define LP_GET_REG_RW_I2C0_DMA_HS_SEL        LP_GET_REG32_BITS(LP_REG_RW_I2C0_DMA_HS_SEL)
#define LP_SET_REG_RW_I2C0_DMA_HS_SEL(x)     LP_SET_REG32_BITS(LP_REG_RW_I2C0_DMA_HS_SEL,x)
#define LP_GET_REG_RW_VAD_DMA_HS_SEL         LP_GET_REG32_BITS(LP_REG_RW_VAD_DMA_HS_SEL)
#define LP_SET_REG_RW_VAD_DMA_HS_SEL(x)      LP_SET_REG32_BITS(LP_REG_RW_VAD_DMA_HS_SEL,x)
#define LP_GET_REG_RW_UART0_DMA_HS_SEL       LP_GET_REG32_BITS(LP_REG_RW_UART0_DMA_HS_SEL)
#define LP_SET_REG_RW_UART0_DMA_HS_SEL(x)    LP_SET_REG32_BITS(LP_REG_RW_UART0_DMA_HS_SEL,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_0        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_0)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_0(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_0,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_1        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_1)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_1(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_1,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_2        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_2)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_2(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_2,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_3        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_3)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_3(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_3,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_4        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_4)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_4(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_4,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_5        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_5)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_5(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_5,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_6        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_6)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_6(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_6,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_7        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_7)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_7(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_7,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_8        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_8)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_8(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_8,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_9        LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_9)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_9(x)     LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_9,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_10       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_10)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_10(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_10,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_11       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_11)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_11(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_11,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_12       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_12)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_12(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_12,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_13       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_13)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_13(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_13,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_14       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_14)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_14(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_14,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_15       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_15)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_15(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_15,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_16       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_16)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_16(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_16,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_17       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_17)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_17(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_17,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_18       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_18)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_18(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_18,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_19       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_19)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_19(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_19,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_20       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_20)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_20(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_20,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_21       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_21)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_21(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_21,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_22       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_22)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_22(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_22,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_23       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_23)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_23(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_23,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_24       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_24)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_24(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_24,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_25       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_25)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_25(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_25,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_26       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_26)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_26(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_26,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_27       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_27)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_27(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_27,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_28       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_28)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_28(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_28,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_29       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_29)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_29(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_29,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_30       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_30)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_30(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_30,x)
#define LP_GET_REG_RW_IP_DMA_HS_SEL_31       LP_GET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_31)
#define LP_SET_REG_RW_IP_DMA_HS_SEL_31(x)    LP_SET_REG32_BITS(LP_REG_RW_IP_DMA_HS_SEL_31,x)

////////////////////////////////////////////////////////////////
// reg group                                                  //
////////////////////////////////////////////////////////////////
#define LP_CM3_ADDR   (LP_CFG_BASE+0x000)
#define LP_INTR_ADDR  (LP_CFG_BASE+0x030)
#define LP_CLKEN_ADDR (LP_CFG_BASE+0x100)
#define LP_DMAHS_ADDR (LP_CFG_BASE+0x200)
#define LP_CACHE_ADDR (LP_CFG_BASE+0x300)

typedef struct {
    // 0x000
    uint32_t reg_rw_m3_stcalib;
    // 0x004
    uint32_t reg_rw_m3_auxfault;
    // 0x008
    uint32_t reg_rw_m3_mpudisable;
    // 0x00c
    uint32_t reg_ro_m3_brchstat        :  4;  //  3 :  0
    uint32_t reg_ro_m3_halted          :  1;  //  4 :  4
    uint32_t reg_ro_m3_lockup          :  1;  //  5 :  5
    uint32_t reg_ro_m3_sleepdeep       :  1;  //  6 :  6
    uint32_t reg_ro_m3_etmintnum       :  9;  // 15 :  7
    uint32_t reg_ro_m3_etmintstat      :  3;  // 18 : 16
    uint32_t reg_ro_m3_currpri         :  8;  // 26 : 19
    uint32_t _reserved0                :  5;  // 31 : 27
    // 0x010
    uint32_t reg_ro_m3_internalstate_0;
    // 0x014
    uint32_t reg_ro_m3_internalstate_1;
    // 0x018
    uint32_t reg_ro_m3_internalstate_2;
    // 0x01c
    uint32_t reg_ro_m3_internalstate_3;
    // 0x020
    uint32_t reg_ro_m3_internalstate_4;
} lp_cm3;

typedef struct {
    // 0x030
    uint32_t reg_rw_intr_mask_0;
    // 0x034
    uint32_t reg_rw_intr_mask_1;
    // 0x038
    uint32_t reg_rw_intr_mask_2;
    // 0x03c
    uint32_t reg_rw_intr_mask_3;
} lp_intr;

typedef struct {
    // 0x100
    uint32_t reg_rw_m3_clk_en;
    // 0x104
    uint32_t reg_rw_dap_clk_en;
    // 0x108
    uint32_t reg_rw_dmac0_clk_en;
    // 0x10c
    uint32_t reg_rw_bootrom0_clk_en;
    // 0x110
    uint32_t reg_rw_vad_cfgclk_en     :  1;  //  0 :  0
    uint32_t reg_rw_vad_clk_en        :  1;  //  1 :  1
    uint32_t _reserved0               : 30;  // 31 :  2
    // 0x114
    uint32_t reg_rw_uart0_cfgclk_en   :  1;  //  0 :  0
    uint32_t reg_rw_uart0_clk_en      :  1;  //  1 :  1
    uint32_t _reserved1               : 30;  // 31 :  2
    // 0x118
    uint32_t reg_rw_i2c0_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_i2c0_clk_en       :  1;  //  1 :  1
    uint32_t _reserved2               : 30;  // 31 :  2
    // 0x11c
    uint32_t reg_rw_timer0_cfgclk_en;
    // 0x120
    uint32_t reg_rw_i2s0_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_i2s0_clk_en       :  1;  //  1 :  1
    uint32_t _reserved3               : 30;  // 31 :  2
    // 0x124
    uint32_t reg_rw_mailbox_cfgclk_en;
    // 0x128
    uint32_t reg_rw_pdm0_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_pdm0_clk_en       :  1;  //  1 :  1
    uint32_t _reserved4               : 30;  // 31 :  2
    // 0x12c
    uint32_t reg_rw_pdm1_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_pdm1_clk_en       :  1;  //  1 :  1
    uint32_t _reserved5               : 30;  // 31 :  2
    // 0x130
    uint32_t reg_rw_pdm2_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_pdm2_clk_en       :  1;  //  1 :  1
    uint32_t _reserved6               : 30;  // 31 :  2
    // 0x134
    uint32_t reg_rw_pdm3_cfgclk_en    :  1;  //  0 :  0
    uint32_t reg_rw_pdm3_clk_en       :  1;  //  1 :  1
    uint32_t _reserved7               : 30;  // 31 :  2
    // 0x138
    uint32_t reg_rw_wdt0_cfgclk_en;
} lp_clken;

typedef struct {
    // 0x200
    uint32_t reg_rw_pdm0_dma_hs_sel  :  3;  //  2 :  0
    uint32_t _reserved0              :  5;  //  7 :  3
    uint32_t reg_rw_pdm1_dma_hs_sel  :  3;  // 10 :  8
    uint32_t _reserved1              :  5;  // 15 : 11
    uint32_t reg_rw_pdm2_dma_hs_sel  :  3;  // 18 : 16
    uint32_t _reserved2              :  5;  // 23 : 19
    uint32_t reg_rw_pdm3_dma_hs_sel  :  3;  // 26 : 24
    uint32_t _reserved3              :  1;  // 27 : 27
    uint32_t reg_rw_i2s0_dma_hs_sel  :  3;  // 30 : 28
    uint32_t _reserved4              :  1;  // 31 : 31
    // 0x204
    uint32_t reg_rw_i2c0_dma_hs_sel  :  2;  //  1 :  0
    uint32_t _reserved5              :  2;  //  3 :  2
    uint32_t reg_rw_vad_dma_hs_sel   :  2;  //  5 :  4
    uint32_t _reserved6              :  2;  //  7 :  6
    uint32_t reg_rw_uart0_dma_hs_sel :  2;  //  9 :  8
    uint32_t _reserved7              : 22;  // 31 : 10
    // 0x208
    uint32_t reg_rw_ip_dma_hs_sel_0  : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_1  : 16;  // 31 : 16
    // 0x20c
    uint32_t reg_rw_ip_dma_hs_sel_2  : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_3  : 16;  // 31 : 16
    // 0x210
    uint32_t reg_rw_ip_dma_hs_sel_4  : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_5  : 16;  // 31 : 16
    // 0x214
    uint32_t reg_rw_ip_dma_hs_sel_6  : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_7  : 16;  // 31 : 16
    // 0x218
    uint32_t reg_rw_ip_dma_hs_sel_8  : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_9  : 16;  // 31 : 16
    // 0x21c
    uint32_t reg_rw_ip_dma_hs_sel_10 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_11 : 16;  // 31 : 16
    // 0x220
    uint32_t reg_rw_ip_dma_hs_sel_12 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_13 : 16;  // 31 : 16
    // 0x224
    uint32_t reg_rw_ip_dma_hs_sel_14 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_15 : 16;  // 31 : 16
    // 0x228
    uint32_t reg_rw_ip_dma_hs_sel_16 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_17 : 16;  // 31 : 16
    // 0x22c
    uint32_t reg_rw_ip_dma_hs_sel_18 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_19 : 16;  // 31 : 16
    // 0x230
    uint32_t reg_rw_ip_dma_hs_sel_20 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_21 : 16;  // 31 : 16
    // 0x234
    uint32_t reg_rw_ip_dma_hs_sel_22 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_23 : 16;  // 31 : 16
    // 0x238
    uint32_t reg_rw_ip_dma_hs_sel_24 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_25 : 16;  // 31 : 16
    // 0x23c
    uint32_t reg_rw_ip_dma_hs_sel_26 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_27 : 16;  // 31 : 16
    // 0x240
    uint32_t reg_rw_ip_dma_hs_sel_28 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_29 : 16;  // 31 : 16
    // 0x244
    uint32_t reg_rw_ip_dma_hs_sel_30 : 16;  // 15 :  0
    uint32_t reg_rw_ip_dma_hs_sel_31 : 16;  // 31 : 16
    // 0x248
    uint32_t reg_rw_ip_dma_hs_sel_32;
} lp_dmahs;

typedef struct {
    // 0x300
    uint32_t reg_rw_icache_en;
} lp_cache;

#define LP_CM3   ((volatile lp_cm3*  )LP_CM3_ADDR  )
#define LP_INTR  ((volatile lp_intr* )LP_INTR_ADDR )
#define LP_CLKEN ((volatile lp_clken*)LP_CLKEN_ADDR)
#define LP_DMAHS ((volatile lp_dmahs*)LP_DMAHS_ADDR)
#define LP_CACHE ((volatile lp_cache*)LP_CACHE_ADDR)


#ifdef __cplusplus
    }
#endif


#endif // __LP_REGS_H__

// vim:set ts=4 sw=4 et fenc=utf-8 fdm=marker:
