// Generated by gen_regs.tcl
// DO NOT EDIT THIS FILE

#ifndef __PERI1_REGS_H__
#define __PERI1_REGS_H__

#include <stdint.h>
#include "chip_mem_layout.h"

////////////////////////////////////////////////////////////////
// baisc reg info                                             //
////////////////////////////////////////////////////////////////

#define PERI1_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT_ADDR               (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT_LSB                0
#define PERI1_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT_MASK               0x00000003

#define PERI1_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH_ADDR               (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH_LSB                2
#define PERI1_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH_MASK               0x0000000c

#define PERI1_REG_RW_USBCTRL_HOST_NUM_U2_PORT_ADDR                   (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_NUM_U2_PORT_LSB                    4
#define PERI1_REG_RW_USBCTRL_HOST_NUM_U2_PORT_MASK                   0x000000f0

#define PERI1_REG_RW_USBCTRL_HOST_NUM_U3_PORT_ADDR                   (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_NUM_U3_PORT_LSB                    8
#define PERI1_REG_RW_USBCTRL_HOST_NUM_U3_PORT_MASK                   0x00000f00

#define PERI1_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE_ADDR               (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE_LSB                12
#define PERI1_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE_MASK               0x00001000

#define PERI1_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE_ADDR               (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE_LSB                13
#define PERI1_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE_MASK               0x00002000

#define PERI1_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT_ADDR    (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT_LSB     16
#define PERI1_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT_MASK    0x00010000

#define PERI1_REG_RW_USBCTRL_HOST_MSI_ENABLE_ADDR                    (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_HOST_MSI_ENABLE_LSB                     17
#define PERI1_REG_RW_USBCTRL_HOST_MSI_ENABLE_MASK                    0x00020000

#define PERI1_REG_RW_USBCTRL_BUS_FILTER_BYPASS_ADDR                  (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_BUS_FILTER_BYPASS_LSB                   18
#define PERI1_REG_RW_USBCTRL_BUS_FILTER_BYPASS_MASK                  0x003c0000

#define PERI1_REG_RO_USBCTRL_PIPE3_POWERPRESENT_ADDR                 (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RO_USBCTRL_PIPE3_POWERPRESENT_LSB                  22
#define PERI1_REG_RO_USBCTRL_PIPE3_POWERPRESENT_MASK                 0x00400000

#define PERI1_REG_RO_USBCTRL_UTMIOTG_VBUSVALID_ADDR                  (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RO_USBCTRL_UTMIOTG_VBUSVALID_LSB                   23
#define PERI1_REG_RO_USBCTRL_UTMIOTG_VBUSVALID_MASK                  0x00800000

#define PERI1_REG_RW_USB_DBG_MODE_ADDR                               (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USB_DBG_MODE_LSB                                24
#define PERI1_REG_RW_USB_DBG_MODE_MASK                               0x07000000

#define PERI1_REG_RW_USBCTRL_UTMISRP_BVALID_ADDR                     (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_UTMISRP_BVALID_LSB                      27
#define PERI1_REG_RW_USBCTRL_UTMISRP_BVALID_MASK                     0x08000000

#define PERI1_REG_RW_USBCTRL_PIPE3_POWERPRESENT_ADDR                 (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_PIPE3_POWERPRESENT_LSB                  28
#define PERI1_REG_RW_USBCTRL_PIPE3_POWERPRESENT_MASK                 0x10000000

#define PERI1_REG_RW_USBCTRL_UTMIOTG_VBUSVALID_ADDR                  (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_UTMIOTG_VBUSVALID_LSB                   29
#define PERI1_REG_RW_USBCTRL_UTMIOTG_VBUSVALID_MASK                  0x20000000

#define PERI1_REG_RW_USBCTRL_VBUSDET_MODE_ADDR                       (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_VBUSDET_MODE_LSB                        30
#define PERI1_REG_RW_USBCTRL_VBUSDET_MODE_MASK                       0x40000000

#define PERI1_REG_RW_USBCTRL_PIPE_DATAWIDTH_ADDR                     (PERI1_REGS_BASE+0x000)
#define PERI1_REG_RW_USBCTRL_PIPE_DATAWIDTH_LSB                      31
#define PERI1_REG_RW_USBCTRL_PIPE_DATAWIDTH_MASK                     0x80000000

#define PERI1_REG_RW_USBCTRL_STARTRXDETU3RXDET_ADDR                  (PERI1_REGS_BASE+0x004)
#define PERI1_REG_RW_USBCTRL_STARTRXDETU3RXDET_LSB                   0
#define PERI1_REG_RW_USBCTRL_STARTRXDETU3RXDET_MASK                  0x00000001

#define PERI1_REG_RW_USBCTRL_DISRXDETU3RXDET_ADDR                    (PERI1_REGS_BASE+0x004)
#define PERI1_REG_RW_USBCTRL_DISRXDETU3RXDET_LSB                     1
#define PERI1_REG_RW_USBCTRL_DISRXDETU3RXDET_MASK                    0x00000002

#define PERI1_REG_RO_USBCTRL_DISRXDETU3RXDET_ACK_ADDR                (PERI1_REGS_BASE+0x004)
#define PERI1_REG_RO_USBCTRL_DISRXDETU3RXDET_ACK_LSB                 2
#define PERI1_REG_RO_USBCTRL_DISRXDETU3RXDET_ACK_MASK                0x00000004

#define PERI1_REG_RO_USBCTRL_HOST_CURRENT_BELT_ADDR                  (PERI1_REGS_BASE+0x008)
#define PERI1_REG_RO_USBCTRL_HOST_CURRENT_BELT_LSB                   0
#define PERI1_REG_RO_USBCTRL_HOST_CURRENT_BELT_MASK                  0x00000fff

#define PERI1_REG_RO_USBCTRL_HOST_SYSTEM_ERR_ADDR                    (PERI1_REGS_BASE+0x008)
#define PERI1_REG_RO_USBCTRL_HOST_SYSTEM_ERR_LSB                     12
#define PERI1_REG_RO_USBCTRL_HOST_SYSTEM_ERR_MASK                    0x00001000

#define PERI1_REG_RW_USBCTRL_XHC_BME_ADDR                            (PERI1_REGS_BASE+0x008)
#define PERI1_REG_RW_USBCTRL_XHC_BME_LSB                             24
#define PERI1_REG_RW_USBCTRL_XHC_BME_MASK                            0x01000000

#define PERI1_REG_RW_USBCTRL_FLADJ_30MHZ_REG_ADDR                    (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RW_USBCTRL_FLADJ_30MHZ_REG_LSB                     0
#define PERI1_REG_RW_USBCTRL_FLADJ_30MHZ_REG_MASK                    0x0000003f

#define PERI1_REG_RW_USBCTRL_PME_EN_ADDR                             (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RW_USBCTRL_PME_EN_LSB                              6
#define PERI1_REG_RW_USBCTRL_PME_EN_MASK                             0x00000040

#define PERI1_REG_RO_USBCTRL_OPERATIONAL_MODE_ADDR                   (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RO_USBCTRL_OPERATIONAL_MODE_LSB                    7
#define PERI1_REG_RO_USBCTRL_OPERATIONAL_MODE_MASK                   0x00000180

#define PERI1_REG_RO_USBCTRL_CLK_GATE_CTRL_ADDR                      (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RO_USBCTRL_CLK_GATE_CTRL_LSB                       9
#define PERI1_REG_RO_USBCTRL_CLK_GATE_CTRL_MASK                      0x00000600

#define PERI1_REG_RO_USBCTRL_PME_GENERATION_ADDR                     (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RO_USBCTRL_PME_GENERATION_LSB                      11
#define PERI1_REG_RO_USBCTRL_PME_GENERATION_MASK                     0x00000800

#define PERI1_REG_RO_USBCTRL_UTMISRP_BVALID_ADDR                     (PERI1_REGS_BASE+0x00c)
#define PERI1_REG_RO_USBCTRL_UTMISRP_BVALID_LSB                      12
#define PERI1_REG_RO_USBCTRL_UTMISRP_BVALID_MASK                     0x00001000

#define PERI1_REG_RW_USBPHY_VCONTROL_ADDR                            (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_VCONTROL_LSB                             0
#define PERI1_REG_RW_USBPHY_VCONTROL_MASK                            0x0000003f

#define PERI1_REG_RW_USBPHY_VCONTROLLOADM_ADDR                       (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_VCONTROLLOADM_LSB                        6
#define PERI1_REG_RW_USBPHY_VCONTROLLOADM_MASK                       0x00000040

#define PERI1_REG_RW_USBPHY_LFPSRX_EN_ADDR                           (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_LFPSRX_EN_LSB                            7
#define PERI1_REG_RW_USBPHY_LFPSRX_EN_MASK                           0x00000080

#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBE_ADDR                    (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBE_LSB                     8
#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBE_MASK                    0x00000100

#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBEH_ADDR                   (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBEH_LSB                    9
#define PERI1_REG_RW_USBPHY_TXBITSTUFFENALBEH_MASK                   0x00000200

#define PERI1_REG_RW_USBPHY_XTLSEL_ADDR                              (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_XTLSEL_LSB                               10
#define PERI1_REG_RW_USBPHY_XTLSEL_MASK                              0x00001c00

#define PERI1_REG_RW_USBPHY_PLL_EN_ADDR                              (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_PLL_EN_LSB                               13
#define PERI1_REG_RW_USBPHY_PLL_EN_MASK                              0x00002000

#define PERI1_REG_RW_USBPHY_U31_CTLE_OFF_ADDR                        (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_U31_CTLE_OFF_LSB                         14
#define PERI1_REG_RW_USBPHY_U31_CTLE_OFF_MASK                        0x00004000

#define PERI1_REG_RW_USBPHY_U31_SSCG_ON_ADDR                         (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_U31_SSCG_ON_LSB                          15
#define PERI1_REG_RW_USBPHY_U31_SSCG_ON_MASK                         0x00008000

#define PERI1_REG_RW_USBPHY_LPM_ALIVE_ADDR                           (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_LPM_ALIVE_LSB                            16
#define PERI1_REG_RW_USBPHY_LPM_ALIVE_MASK                           0x00010000

#define PERI1_REG_RW_USBPHY_HS_BIST_MODE_ADDR                        (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_HS_BIST_MODE_LSB                         17
#define PERI1_REG_RW_USBPHY_HS_BIST_MODE_MASK                        0x00020000

#define PERI1_REG_RW_USBPHY_LS_EN_ADDR                               (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_LS_EN_LSB                                18
#define PERI1_REG_RW_USBPHY_LS_EN_MASK                               0x00040000

#define PERI1_REG_RW_USBPHY_DEBUGSEL_ADDR                            (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_DEBUGSEL_LSB                             19
#define PERI1_REG_RW_USBPHY_DEBUGSEL_MASK                            0x01f80000

#define PERI1_REG_RW_USBPHY_SCAN_CHAIN_CONNECT_ADDR                  (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_SCAN_CHAIN_CONNECT_LSB                   25
#define PERI1_REG_RW_USBPHY_SCAN_CHAIN_CONNECT_MASK                  0x02000000

#define PERI1_REG_RW_USBPHY_INTERNALLOOPBACK_ADDR                    (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_INTERNALLOOPBACK_LSB                     26
#define PERI1_REG_RW_USBPHY_INTERNALLOOPBACK_MASK                    0x04000000

#define PERI1_REG_RW_USBPHY_CC_EN_ADDR                               (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_CC_EN_LSB                                28
#define PERI1_REG_RW_USBPHY_CC_EN_MASK                               0x10000000

#define PERI1_REG_RW_USBPHY_CC_LPF_OPT_ADDR                          (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_CC_LPF_OPT_LSB                           30
#define PERI1_REG_RW_USBPHY_CC_LPF_OPT_MASK                          0x40000000

#define PERI1_REG_RW_USBPHY_IDPAD_EN_ADDR                            (PERI1_REGS_BASE+0x010)
#define PERI1_REG_RW_USBPHY_IDPAD_EN_LSB                             31
#define PERI1_REG_RW_USBPHY_IDPAD_EN_MASK                            0x80000000

#define PERI1_REG_RW_USBPHY_CC_RD_EN_ADDR                            (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_RD_EN_LSB                             0
#define PERI1_REG_RW_USBPHY_CC_RD_EN_MASK                            0x00000001

#define PERI1_REG_RW_USBPHY_CC_RP_3D0_EN_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_RP_3D0_EN_LSB                         1
#define PERI1_REG_RW_USBPHY_CC_RP_3D0_EN_MASK                        0x00000002

#define PERI1_REG_RW_USBPHY_CC_RP_1D5_EN_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_RP_1D5_EN_LSB                         2
#define PERI1_REG_RW_USBPHY_CC_RP_1D5_EN_MASK                        0x00000004

#define PERI1_REG_RW_USBPHY_CC_RP_0D9_EN_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_RP_0D9_EN_LSB                         3
#define PERI1_REG_RW_USBPHY_CC_RP_0D9_EN_MASK                        0x00000008

#define PERI1_REG_RW_USBPHY_CC_REF_OPT_ADDR                          (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_REF_OPT_LSB                           6
#define PERI1_REG_RW_USBPHY_CC_REF_OPT_MASK                          0x000001c0

#define PERI1_REG_RW_USBPHY_U31_HOST_PHY_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_U31_HOST_PHY_LSB                         16
#define PERI1_REG_RW_USBPHY_U31_HOST_PHY_MASK                        0x00010000

#define PERI1_REG_RW_USB_CC_DET_MODE_ADDR                            (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USB_CC_DET_MODE_LSB                             17
#define PERI1_REG_RW_USB_CC_DET_MODE_MASK                            0x00020000

#define PERI1_REG_RW_USBPHY_CC_HOST_EN_ADDR                          (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_CC_HOST_EN_LSB                           18
#define PERI1_REG_RW_USBPHY_CC_HOST_EN_MASK                          0x00040000

#define PERI1_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG_ADDR                 (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG_LSB                  19
#define PERI1_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG_MASK                 0x00080000

#define PERI1_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG_ADDR                 (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG_LSB                  20
#define PERI1_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG_MASK                 0x00100000

#define PERI1_REG_RO_USBPHY_U31_SSTX_SEL_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RO_USBPHY_U31_SSTX_SEL_LSB                         21
#define PERI1_REG_RO_USBPHY_U31_SSTX_SEL_MASK                        0x00200000

#define PERI1_REG_RO_USBPHY_U31_SSRX_SEL_ADDR                        (PERI1_REGS_BASE+0x014)
#define PERI1_REG_RO_USBPHY_U31_SSRX_SEL_LSB                         22
#define PERI1_REG_RO_USBPHY_U31_SSRX_SEL_MASK                        0x00400000

#define PERI1_REG_RW_USBPHY_XCFGI0_ADDR                              (PERI1_REGS_BASE+0x018)

#define PERI1_REG_RW_USBPHY_XCFGI1_ADDR                              (PERI1_REGS_BASE+0x01c)

#define PERI1_REG_RW_USBPHY_XCFGI2_ADDR                              (PERI1_REGS_BASE+0x020)

#define PERI1_REG_RW_USBPHY_XCFGI3_ADDR                              (PERI1_REGS_BASE+0x024)

#define PERI1_REG_RW_USBPHY_XCFGI4_ADDR                              (PERI1_REGS_BASE+0x028)

#define PERI1_REG_RW_USBPHY_XCFGI5_ADDR                              (PERI1_REGS_BASE+0x02c)

#define PERI1_REG_RW_USBPHY_XCFGI6_ADDR                              (PERI1_REGS_BASE+0x030)

#define PERI1_REG_RW_USBPHY_XCFGI7_ADDR                              (PERI1_REGS_BASE+0x034)

#define PERI1_REG_RW_USBPHY_XCFGI8_ADDR                              (PERI1_REGS_BASE+0x038)

#define PERI1_REG_RW_USBPHY_XCFGI9_ADDR                              (PERI1_REGS_BASE+0x03c)

#define PERI1_REG_RW_USBPHY_XCFGI10_ADDR                             (PERI1_REGS_BASE+0x040)

#define PERI1_REG_RW_USBPHY_XCFGI11_ADDR                             (PERI1_REGS_BASE+0x044)

#define PERI1_REG_RW_USBPHY_XCFGI12_ADDR                             (PERI1_REGS_BASE+0x048)

#define PERI1_REG_RW_USBPHY_XCFGI13_ADDR                             (PERI1_REGS_BASE+0x04c)

#define PERI1_REG_RW_USBPHY_XCFGI14_ADDR                             (PERI1_REGS_BASE+0x050)

#define PERI1_REG_RW_USBPHY_XCFGI15_ADDR                             (PERI1_REGS_BASE+0x054)

#define PERI1_REG_RW_USBPHY_XCFGI16_ADDR                             (PERI1_REGS_BASE+0x058)

#define PERI1_REG_RW_USBPHY_XCFGI17_ADDR                             (PERI1_REGS_BASE+0x05c)

#define PERI1_REG_RW_USBPHY_XCFGI18_ADDR                             (PERI1_REGS_BASE+0x060)

#define PERI1_REG_RW_USBPHY_XCFGI19_ADDR                             (PERI1_REGS_BASE+0x064)

#define PERI1_REG_RW_USBPHY_XCFGI20_ADDR                             (PERI1_REGS_BASE+0x068)

#define PERI1_REG_RW_USBPHY_XCFGI21_ADDR                             (PERI1_REGS_BASE+0x06c)

#define PERI1_REG_RW_USBPHY_XCFGI22_ADDR                             (PERI1_REGS_BASE+0x070)

#define PERI1_REG_RW_USBPHY_XCFGI23_ADDR                             (PERI1_REGS_BASE+0x074)

#define PERI1_REG_RO_USBPHY_BIST_OK_U2_ADDR                          (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_BIST_OK_U2_LSB                           0
#define PERI1_REG_RO_USBPHY_BIST_OK_U2_MASK                          0x00000001

#define PERI1_REG_RO_USBPHY_BIST_OK_U3_ADDR                          (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_BIST_OK_U3_LSB                           1
#define PERI1_REG_RO_USBPHY_BIST_OK_U3_MASK                          0x00000002

#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_0_ADDR                     (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_0_LSB                      4
#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_0_MASK                     0x00000010

#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_0_ADDR                       (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_0_LSB                        5
#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_0_MASK                       0x00000020

#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_0_ADDR                       (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_0_LSB                        6
#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_0_MASK                       0x00000040

#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_0_ADDR                 (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_0_LSB                  7
#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_0_MASK                 0x00000080

#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_0_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_0_LSB                         8
#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_0_MASK                        0x00000100

#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_0_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_0_LSB                         9
#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_0_MASK                        0x00000200

#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_0_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_0_LSB                         10
#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_0_MASK                        0x00000400

#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_1_ADDR                     (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_1_LSB                      11
#define PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_1_MASK                     0x00000800

#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_1_ADDR                       (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_1_LSB                        12
#define PERI1_REG_RO_USBPHY_CC_HOST_VRD_1_MASK                       0x00001000

#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_1_ADDR                       (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_1_LSB                        13
#define PERI1_REG_RO_USBPHY_CC_HOST_VRA_1_MASK                       0x00002000

#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_1_ADDR                 (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_1_LSB                  14
#define PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_1_MASK                 0x00004000

#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_1_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_1_LSB                         15
#define PERI1_REG_RO_USBPHY_CC_OUT_3D0_1_MASK                        0x00008000

#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_1_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_1_LSB                         16
#define PERI1_REG_RO_USBPHY_CC_OUT_1D5_1_MASK                        0x00010000

#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_1_ADDR                        (PERI1_REGS_BASE+0x078)
#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_1_LSB                         17
#define PERI1_REG_RO_USBPHY_CC_OUT_0D9_1_MASK                        0x00020000

#define PERI1_REG_RO_USBPHY_XCFGO0_ADDR                              (PERI1_REGS_BASE+0x07c)

#define PERI1_REG_RO_USBPHY_XCFGO1_ADDR                              (PERI1_REGS_BASE+0x080)

#define PERI1_REG_RO_USBPHY_XCFGO2_ADDR                              (PERI1_REGS_BASE+0x084)

#define PERI1_REG_RW_PKA_CFG_RW_MEM_MASK_ADDR                        (PERI1_REGS_BASE+0x088)
#define PERI1_REG_RW_PKA_CFG_RW_MEM_MASK_LSB                         0
#define PERI1_REG_RW_PKA_CFG_RW_MEM_MASK_MASK                        0x0000003f

#define PERI1_REG_RW_PKA_DPA_DISABLE_ADDR                            (PERI1_REGS_BASE+0x088)
#define PERI1_REG_RW_PKA_DPA_DISABLE_LSB                             6
#define PERI1_REG_RW_PKA_DPA_DISABLE_MASK                            0x00000040

#define PERI1_REG_RW_PKA_NOISE_SRC_ADDR                              (PERI1_REGS_BASE+0x088)
#define PERI1_REG_RW_PKA_NOISE_SRC_LSB                               7
#define PERI1_REG_RW_PKA_NOISE_SRC_MASK                              0x00000080

#define PERI1_REG_RW_PKA_NOISE_SRC_VALID_ADDR                        (PERI1_REGS_BASE+0x088)
#define PERI1_REG_RW_PKA_NOISE_SRC_VALID_LSB                         8
#define PERI1_REG_RW_PKA_NOISE_SRC_VALID_MASK                        0x00000100

#define PERI1_REG_RW_PKA_CFG_CLK_EN_ADDR                             (PERI1_REGS_BASE+0x088)
#define PERI1_REG_RW_PKA_CFG_CLK_EN_LSB                              9
#define PERI1_REG_RW_PKA_CFG_CLK_EN_MASK                             0x00000200

#define PERI1_REG_RW_SPI0_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x100)
#define PERI1_REG_RW_SPI0_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_SPI0_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_SPI0_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x100)
#define PERI1_REG_RW_SPI0_CLK_EN_LSB                                 1
#define PERI1_REG_RW_SPI0_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_SPI1_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x104)
#define PERI1_REG_RW_SPI1_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_SPI1_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_SPI1_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x104)
#define PERI1_REG_RW_SPI1_CLK_EN_LSB                                 1
#define PERI1_REG_RW_SPI1_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_SPI2_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x108)
#define PERI1_REG_RW_SPI2_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_SPI2_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_SPI2_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x108)
#define PERI1_REG_RW_SPI2_CLK_EN_LSB                                 1
#define PERI1_REG_RW_SPI2_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_SPI_SLV_CFG_CLK_EN_ADDR                         (PERI1_REGS_BASE+0x10c)
#define PERI1_REG_RW_SPI_SLV_CFG_CLK_EN_LSB                          0
#define PERI1_REG_RW_SPI_SLV_CFG_CLK_EN_MASK                         0x00000001

#define PERI1_REG_RW_SPI_SLV_CLK_EN_ADDR                             (PERI1_REGS_BASE+0x10c)
#define PERI1_REG_RW_SPI_SLV_CLK_EN_LSB                              1
#define PERI1_REG_RW_SPI_SLV_CLK_EN_MASK                             0x00000002

#define PERI1_REG_RW_PWM1_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x110)
#define PERI1_REG_RW_PWM1_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM1_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM1_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x110)
#define PERI1_REG_RW_PWM1_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM1_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM2_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x114)
#define PERI1_REG_RW_PWM2_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM2_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM2_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x114)
#define PERI1_REG_RW_PWM2_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM2_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM3_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x118)
#define PERI1_REG_RW_PWM3_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM3_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM3_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x118)
#define PERI1_REG_RW_PWM3_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM3_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM4_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x11c)
#define PERI1_REG_RW_PWM4_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM4_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM4_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x11c)
#define PERI1_REG_RW_PWM4_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM4_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM5_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x120)
#define PERI1_REG_RW_PWM5_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM5_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM5_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x120)
#define PERI1_REG_RW_PWM5_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM5_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM6_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x124)
#define PERI1_REG_RW_PWM6_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM6_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM6_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x124)
#define PERI1_REG_RW_PWM6_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM6_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_PWM7_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x128)
#define PERI1_REG_RW_PWM7_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_PWM7_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_PWM7_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x128)
#define PERI1_REG_RW_PWM7_CLK_EN_LSB                                 1
#define PERI1_REG_RW_PWM7_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_I2C5_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x12c)
#define PERI1_REG_RW_I2C5_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_I2C5_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_I2C5_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x12c)
#define PERI1_REG_RW_I2C5_CLK_EN_LSB                                 1
#define PERI1_REG_RW_I2C5_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_I2C6_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x130)
#define PERI1_REG_RW_I2C6_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_I2C6_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_I2C6_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x130)
#define PERI1_REG_RW_I2C6_CLK_EN_LSB                                 1
#define PERI1_REG_RW_I2C6_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_UART3_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x134)
#define PERI1_REG_RW_UART3_CFG_CLK_EN_LSB                            0
#define PERI1_REG_RW_UART3_CFG_CLK_EN_MASK                           0x00000001

#define PERI1_REG_RW_UART3_CLK_EN_ADDR                               (PERI1_REGS_BASE+0x134)
#define PERI1_REG_RW_UART3_CLK_EN_LSB                                1
#define PERI1_REG_RW_UART3_CLK_EN_MASK                               0x00000002

#define PERI1_REG_RW_UART4_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x138)
#define PERI1_REG_RW_UART4_CFG_CLK_EN_LSB                            0
#define PERI1_REG_RW_UART4_CFG_CLK_EN_MASK                           0x00000001

#define PERI1_REG_RW_UART4_CLK_EN_ADDR                               (PERI1_REGS_BASE+0x138)
#define PERI1_REG_RW_UART4_CLK_EN_LSB                                1
#define PERI1_REG_RW_UART4_CLK_EN_MASK                               0x00000002

#define PERI1_REG_RW_UART5_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x13c)
#define PERI1_REG_RW_UART5_CFG_CLK_EN_LSB                            0
#define PERI1_REG_RW_UART5_CFG_CLK_EN_MASK                           0x00000001

#define PERI1_REG_RW_UART5_CLK_EN_ADDR                               (PERI1_REGS_BASE+0x13c)
#define PERI1_REG_RW_UART5_CLK_EN_LSB                                1
#define PERI1_REG_RW_UART5_CLK_EN_MASK                               0x00000002

#define PERI1_REG_RW_UART6_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x140)
#define PERI1_REG_RW_UART6_CFG_CLK_EN_LSB                            0
#define PERI1_REG_RW_UART6_CFG_CLK_EN_MASK                           0x00000001

#define PERI1_REG_RW_UART6_CLK_EN_ADDR                               (PERI1_REGS_BASE+0x140)
#define PERI1_REG_RW_UART6_CLK_EN_LSB                                1
#define PERI1_REG_RW_UART6_CLK_EN_MASK                               0x00000002

#define PERI1_REG_RW_UART7_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x144)
#define PERI1_REG_RW_UART7_CFG_CLK_EN_LSB                            0
#define PERI1_REG_RW_UART7_CFG_CLK_EN_MASK                           0x00000001

#define PERI1_REG_RW_UART7_CLK_EN_ADDR                               (PERI1_REGS_BASE+0x144)
#define PERI1_REG_RW_UART7_CLK_EN_LSB                                1
#define PERI1_REG_RW_UART7_CLK_EN_MASK                               0x00000002

#define PERI1_REG_RW_EFUSE_CFG_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x148)

#define PERI1_REG_RW_GMAC_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x14c)

#define PERI1_REG_RW_SPACC_AXI_CLK_EN_ADDR                           (PERI1_REGS_BASE+0x150)

#define PERI1_REG_RW_USBCTRL_CLK_EN_ADDR                             (PERI1_REGS_BASE+0x154)

#define PERI1_REG_RW_I2S3_CFG_CLK_EN_ADDR                            (PERI1_REGS_BASE+0x158)
#define PERI1_REG_RW_I2S3_CFG_CLK_EN_LSB                             0
#define PERI1_REG_RW_I2S3_CFG_CLK_EN_MASK                            0x00000001

#define PERI1_REG_RW_I2S3_CLK_EN_ADDR                                (PERI1_REGS_BASE+0x158)
#define PERI1_REG_RW_I2S3_CLK_EN_LSB                                 1
#define PERI1_REG_RW_I2S3_CLK_EN_MASK                                0x00000002

#define PERI1_REG_RW_SPI0_MST_DMA_HS_SEL_ADDR                        (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_SPI0_MST_DMA_HS_SEL_LSB                         0
#define PERI1_REG_RW_SPI0_MST_DMA_HS_SEL_MASK                        0x00000003

#define PERI1_REG_RW_SPI1_MST_DMA_HS_SEL_ADDR                        (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_SPI1_MST_DMA_HS_SEL_LSB                         2
#define PERI1_REG_RW_SPI1_MST_DMA_HS_SEL_MASK                        0x0000000c

#define PERI1_REG_RW_SPI2_MST_DMA_HS_SEL_ADDR                        (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_SPI2_MST_DMA_HS_SEL_LSB                         4
#define PERI1_REG_RW_SPI2_MST_DMA_HS_SEL_MASK                        0x00000030

#define PERI1_REG_RW_SPI_SLV_DMA_HS_SEL_ADDR                         (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_SPI_SLV_DMA_HS_SEL_LSB                          6
#define PERI1_REG_RW_SPI_SLV_DMA_HS_SEL_MASK                         0x000000c0

#define PERI1_REG_RW_UART3_DMA_HS_SEL_ADDR                           (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_UART3_DMA_HS_SEL_LSB                            8
#define PERI1_REG_RW_UART3_DMA_HS_SEL_MASK                           0x00000300

#define PERI1_REG_RW_I2S3_DMA_HS_SEL_ADDR                            (PERI1_REGS_BASE+0x200)
#define PERI1_REG_RW_I2S3_DMA_HS_SEL_LSB                             10
#define PERI1_REG_RW_I2S3_DMA_HS_SEL_MASK                            0x00000c00

#define PERI1_REG_RW_GMAC_DELAY_COUNT_ADDR                           (PERI1_REGS_BASE+0x204)

#define PERI1_REG_RW_GMAC_REMAP_ADDR                                 (PERI1_REGS_BASE+0x208)

#define PERI1_REG_RW_SPACC_REMAP_ADDR                                (PERI1_REGS_BASE+0x20c)

////////////////////////////////////////////////////////////////
// reg access                                                 //
////////////////////////////////////////////////////////////////
#define PERI1_REG32(name)                                            (*(volatile uint32_t*)name##_ADDR)

#define PERI1_GET_REG_RW_USBPHY_XCFGI0                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI0)
#define PERI1_SET_REG_RW_USBPHY_XCFGI0(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI0) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI1                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI1)
#define PERI1_SET_REG_RW_USBPHY_XCFGI1(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI1) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI2                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI2)
#define PERI1_SET_REG_RW_USBPHY_XCFGI2(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI2) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI3                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI3)
#define PERI1_SET_REG_RW_USBPHY_XCFGI3(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI3) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI4                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI4)
#define PERI1_SET_REG_RW_USBPHY_XCFGI4(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI4) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI5                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI5)
#define PERI1_SET_REG_RW_USBPHY_XCFGI5(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI5) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI6                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI6)
#define PERI1_SET_REG_RW_USBPHY_XCFGI6(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI6) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI7                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI7)
#define PERI1_SET_REG_RW_USBPHY_XCFGI7(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI7) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI8                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI8)
#define PERI1_SET_REG_RW_USBPHY_XCFGI8(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI8) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI9                               PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI9)
#define PERI1_SET_REG_RW_USBPHY_XCFGI9(x)                            PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI9) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI10                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI10)
#define PERI1_SET_REG_RW_USBPHY_XCFGI10(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI10) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI11                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI11)
#define PERI1_SET_REG_RW_USBPHY_XCFGI11(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI11) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI12                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI12)
#define PERI1_SET_REG_RW_USBPHY_XCFGI12(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI12) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI13                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI13)
#define PERI1_SET_REG_RW_USBPHY_XCFGI13(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI13) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI14                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI14)
#define PERI1_SET_REG_RW_USBPHY_XCFGI14(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI14) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI15                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI15)
#define PERI1_SET_REG_RW_USBPHY_XCFGI15(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI15) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI16                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI16)
#define PERI1_SET_REG_RW_USBPHY_XCFGI16(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI16) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI17                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI17)
#define PERI1_SET_REG_RW_USBPHY_XCFGI17(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI17) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI18                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI18)
#define PERI1_SET_REG_RW_USBPHY_XCFGI18(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI18) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI19                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI19)
#define PERI1_SET_REG_RW_USBPHY_XCFGI19(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI19) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI20                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI20)
#define PERI1_SET_REG_RW_USBPHY_XCFGI20(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI20) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI21                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI21)
#define PERI1_SET_REG_RW_USBPHY_XCFGI21(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI21) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI22                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI22)
#define PERI1_SET_REG_RW_USBPHY_XCFGI22(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI22) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBPHY_XCFGI23                              PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI23)
#define PERI1_SET_REG_RW_USBPHY_XCFGI23(x)                           PERI1_REG32(PERI1_REG_RW_USBPHY_XCFGI23) = (uint32_t)(x)
#define PERI1_GET_REG_RO_USBPHY_XCFGO0                               PERI1_REG32(PERI1_REG_RO_USBPHY_XCFGO0)
#define PERI1_GET_REG_RO_USBPHY_XCFGO1                               PERI1_REG32(PERI1_REG_RO_USBPHY_XCFGO1)
#define PERI1_GET_REG_RO_USBPHY_XCFGO2                               PERI1_REG32(PERI1_REG_RO_USBPHY_XCFGO2)
#define PERI1_GET_REG_RW_EFUSE_CFG_CLK_EN                            PERI1_REG32(PERI1_REG_RW_EFUSE_CFG_CLK_EN)
#define PERI1_SET_REG_RW_EFUSE_CFG_CLK_EN(x)                         PERI1_REG32(PERI1_REG_RW_EFUSE_CFG_CLK_EN) = (uint32_t)(x)
#define PERI1_GET_REG_RW_GMAC_CLK_EN                                 PERI1_REG32(PERI1_REG_RW_GMAC_CLK_EN)
#define PERI1_SET_REG_RW_GMAC_CLK_EN(x)                              PERI1_REG32(PERI1_REG_RW_GMAC_CLK_EN) = (uint32_t)(x)
#define PERI1_GET_REG_RW_SPACC_AXI_CLK_EN                            PERI1_REG32(PERI1_REG_RW_SPACC_AXI_CLK_EN)
#define PERI1_SET_REG_RW_SPACC_AXI_CLK_EN(x)                         PERI1_REG32(PERI1_REG_RW_SPACC_AXI_CLK_EN) = (uint32_t)(x)
#define PERI1_GET_REG_RW_USBCTRL_CLK_EN                              PERI1_REG32(PERI1_REG_RW_USBCTRL_CLK_EN)
#define PERI1_SET_REG_RW_USBCTRL_CLK_EN(x)                           PERI1_REG32(PERI1_REG_RW_USBCTRL_CLK_EN) = (uint32_t)(x)
#define PERI1_GET_REG_RW_GMAC_DELAY_COUNT                            PERI1_REG32(PERI1_REG_RW_GMAC_DELAY_COUNT)
#define PERI1_SET_REG_RW_GMAC_DELAY_COUNT(x)                         PERI1_REG32(PERI1_REG_RW_GMAC_DELAY_COUNT) = (uint32_t)(x)
#define PERI1_GET_REG_RW_GMAC_REMAP                                  PERI1_REG32(PERI1_REG_RW_GMAC_REMAP)
#define PERI1_SET_REG_RW_GMAC_REMAP(x)                               PERI1_REG32(PERI1_REG_RW_GMAC_REMAP) = (uint32_t)(x)
#define PERI1_GET_REG_RW_SPACC_REMAP                                 PERI1_REG32(PERI1_REG_RW_SPACC_REMAP)
#define PERI1_SET_REG_RW_SPACC_REMAP(x)                              PERI1_REG32(PERI1_REG_RW_SPACC_REMAP) = (uint32_t)(x)

////////////////////////////////////////////////////////////////
// reg bits access                                            //
////////////////////////////////////////////////////////////////
#define PERI1_GET_REG32_BITS(name)                                   ((PERI1_REG32(name) & name##_MASK) >> name##_LSB)
#define PERI1_SET_REG32_BITS(name,x)                                 do { \
    uint32_t val = PERI1_REG32(name); \
    val &= ~name##_MASK; \
    val |= ((x) << name##_LSB) & name##_MASK; \
    PERI1_REG32(name) = val; \
} while(0)

#define PERI1_GET_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT)
#define PERI1_SET_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT(x)             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HUB_PORT_OVERCURRENT,x)
#define PERI1_GET_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH)
#define PERI1_SET_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH(x)             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HUB_PORT_PERM_ATTACH,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_NUM_U2_PORT                    PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_NUM_U2_PORT)
#define PERI1_SET_REG_RW_USBCTRL_HOST_NUM_U2_PORT(x)                 PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_NUM_U2_PORT,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_NUM_U3_PORT                    PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_NUM_U3_PORT)
#define PERI1_SET_REG_RW_USBCTRL_HOST_NUM_U3_PORT(x)                 PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_NUM_U3_PORT,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE)
#define PERI1_SET_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE(x)             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_U2_PORT_DISABLE,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE)
#define PERI1_SET_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE(x)             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_U3_PORT_DISABLE,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT)
#define PERI1_SET_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT(x)  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_PORT_POWER_CONTROL_PRESENT,x)
#define PERI1_GET_REG_RW_USBCTRL_HOST_MSI_ENABLE                     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_MSI_ENABLE)
#define PERI1_SET_REG_RW_USBCTRL_HOST_MSI_ENABLE(x)                  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_HOST_MSI_ENABLE,x)
#define PERI1_GET_REG_RW_USBCTRL_BUS_FILTER_BYPASS                   PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_BUS_FILTER_BYPASS)
#define PERI1_SET_REG_RW_USBCTRL_BUS_FILTER_BYPASS(x)                PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_BUS_FILTER_BYPASS,x)
#define PERI1_GET_REG_RO_USBCTRL_PIPE3_POWERPRESENT                  PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_PIPE3_POWERPRESENT)
#define PERI1_GET_REG_RO_USBCTRL_UTMIOTG_VBUSVALID                   PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_UTMIOTG_VBUSVALID)
#define PERI1_GET_REG_RW_USB_DBG_MODE                                PERI1_GET_REG32_BITS(PERI1_REG_RW_USB_DBG_MODE)
#define PERI1_SET_REG_RW_USB_DBG_MODE(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_USB_DBG_MODE,x)
#define PERI1_GET_REG_RW_USBCTRL_UTMISRP_BVALID                      PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_UTMISRP_BVALID)
#define PERI1_SET_REG_RW_USBCTRL_UTMISRP_BVALID(x)                   PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_UTMISRP_BVALID,x)
#define PERI1_GET_REG_RW_USBCTRL_PIPE3_POWERPRESENT                  PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_PIPE3_POWERPRESENT)
#define PERI1_SET_REG_RW_USBCTRL_PIPE3_POWERPRESENT(x)               PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_PIPE3_POWERPRESENT,x)
#define PERI1_GET_REG_RW_USBCTRL_UTMIOTG_VBUSVALID                   PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_UTMIOTG_VBUSVALID)
#define PERI1_SET_REG_RW_USBCTRL_UTMIOTG_VBUSVALID(x)                PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_UTMIOTG_VBUSVALID,x)
#define PERI1_GET_REG_RW_USBCTRL_VBUSDET_MODE                        PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_VBUSDET_MODE)
#define PERI1_SET_REG_RW_USBCTRL_VBUSDET_MODE(x)                     PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_VBUSDET_MODE,x)
#define PERI1_GET_REG_RW_USBCTRL_PIPE_DATAWIDTH                      PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_PIPE_DATAWIDTH)
#define PERI1_SET_REG_RW_USBCTRL_PIPE_DATAWIDTH(x)                   PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_PIPE_DATAWIDTH,x)
#define PERI1_GET_REG_RW_USBCTRL_STARTRXDETU3RXDET                   PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_STARTRXDETU3RXDET)
#define PERI1_SET_REG_RW_USBCTRL_STARTRXDETU3RXDET(x)                PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_STARTRXDETU3RXDET,x)
#define PERI1_GET_REG_RW_USBCTRL_DISRXDETU3RXDET                     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_DISRXDETU3RXDET)
#define PERI1_SET_REG_RW_USBCTRL_DISRXDETU3RXDET(x)                  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_DISRXDETU3RXDET,x)
#define PERI1_GET_REG_RO_USBCTRL_DISRXDETU3RXDET_ACK                 PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_DISRXDETU3RXDET_ACK)
#define PERI1_GET_REG_RO_USBCTRL_HOST_CURRENT_BELT                   PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_HOST_CURRENT_BELT)
#define PERI1_GET_REG_RO_USBCTRL_HOST_SYSTEM_ERR                     PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_HOST_SYSTEM_ERR)
#define PERI1_GET_REG_RW_USBCTRL_XHC_BME                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_XHC_BME)
#define PERI1_SET_REG_RW_USBCTRL_XHC_BME(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_XHC_BME,x)
#define PERI1_GET_REG_RW_USBCTRL_FLADJ_30MHZ_REG                     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_FLADJ_30MHZ_REG)
#define PERI1_SET_REG_RW_USBCTRL_FLADJ_30MHZ_REG(x)                  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_FLADJ_30MHZ_REG,x)
#define PERI1_GET_REG_RW_USBCTRL_PME_EN                              PERI1_GET_REG32_BITS(PERI1_REG_RW_USBCTRL_PME_EN)
#define PERI1_SET_REG_RW_USBCTRL_PME_EN(x)                           PERI1_SET_REG32_BITS(PERI1_REG_RW_USBCTRL_PME_EN,x)
#define PERI1_GET_REG_RO_USBCTRL_OPERATIONAL_MODE                    PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_OPERATIONAL_MODE)
#define PERI1_GET_REG_RO_USBCTRL_CLK_GATE_CTRL                       PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_CLK_GATE_CTRL)
#define PERI1_GET_REG_RO_USBCTRL_PME_GENERATION                      PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_PME_GENERATION)
#define PERI1_GET_REG_RO_USBCTRL_UTMISRP_BVALID                      PERI1_GET_REG32_BITS(PERI1_REG_RO_USBCTRL_UTMISRP_BVALID)
#define PERI1_GET_REG_RW_USBPHY_VCONTROL                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_VCONTROL)
#define PERI1_SET_REG_RW_USBPHY_VCONTROL(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_VCONTROL,x)
#define PERI1_GET_REG_RW_USBPHY_VCONTROLLOADM                        PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_VCONTROLLOADM)
#define PERI1_SET_REG_RW_USBPHY_VCONTROLLOADM(x)                     PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_VCONTROLLOADM,x)
#define PERI1_GET_REG_RW_USBPHY_LFPSRX_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_LFPSRX_EN)
#define PERI1_SET_REG_RW_USBPHY_LFPSRX_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_LFPSRX_EN,x)
#define PERI1_GET_REG_RW_USBPHY_TXBITSTUFFENALBE                     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_TXBITSTUFFENALBE)
#define PERI1_SET_REG_RW_USBPHY_TXBITSTUFFENALBE(x)                  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_TXBITSTUFFENALBE,x)
#define PERI1_GET_REG_RW_USBPHY_TXBITSTUFFENALBEH                    PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_TXBITSTUFFENALBEH)
#define PERI1_SET_REG_RW_USBPHY_TXBITSTUFFENALBEH(x)                 PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_TXBITSTUFFENALBEH,x)
#define PERI1_GET_REG_RW_USBPHY_XTLSEL                               PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_XTLSEL)
#define PERI1_SET_REG_RW_USBPHY_XTLSEL(x)                            PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_XTLSEL,x)
#define PERI1_GET_REG_RW_USBPHY_PLL_EN                               PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_PLL_EN)
#define PERI1_SET_REG_RW_USBPHY_PLL_EN(x)                            PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_PLL_EN,x)
#define PERI1_GET_REG_RW_USBPHY_U31_CTLE_OFF                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_CTLE_OFF)
#define PERI1_SET_REG_RW_USBPHY_U31_CTLE_OFF(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_CTLE_OFF,x)
#define PERI1_GET_REG_RW_USBPHY_U31_SSCG_ON                          PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSCG_ON)
#define PERI1_SET_REG_RW_USBPHY_U31_SSCG_ON(x)                       PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSCG_ON,x)
#define PERI1_GET_REG_RW_USBPHY_LPM_ALIVE                            PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_LPM_ALIVE)
#define PERI1_SET_REG_RW_USBPHY_LPM_ALIVE(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_LPM_ALIVE,x)
#define PERI1_GET_REG_RW_USBPHY_HS_BIST_MODE                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_HS_BIST_MODE)
#define PERI1_SET_REG_RW_USBPHY_HS_BIST_MODE(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_HS_BIST_MODE,x)
#define PERI1_GET_REG_RW_USBPHY_LS_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_LS_EN)
#define PERI1_SET_REG_RW_USBPHY_LS_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_LS_EN,x)
#define PERI1_GET_REG_RW_USBPHY_DEBUGSEL                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_DEBUGSEL)
#define PERI1_SET_REG_RW_USBPHY_DEBUGSEL(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_DEBUGSEL,x)
#define PERI1_GET_REG_RW_USBPHY_SCAN_CHAIN_CONNECT                   PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_SCAN_CHAIN_CONNECT)
#define PERI1_SET_REG_RW_USBPHY_SCAN_CHAIN_CONNECT(x)                PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_SCAN_CHAIN_CONNECT,x)
#define PERI1_GET_REG_RW_USBPHY_INTERNALLOOPBACK                     PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_INTERNALLOOPBACK)
#define PERI1_SET_REG_RW_USBPHY_INTERNALLOOPBACK(x)                  PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_INTERNALLOOPBACK,x)
#define PERI1_GET_REG_RW_USBPHY_CC_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_LPF_OPT                           PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_LPF_OPT)
#define PERI1_SET_REG_RW_USBPHY_CC_LPF_OPT(x)                        PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_LPF_OPT,x)
#define PERI1_GET_REG_RW_USBPHY_IDPAD_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_IDPAD_EN)
#define PERI1_SET_REG_RW_USBPHY_IDPAD_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_IDPAD_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_RD_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RD_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_RD_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RD_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_RP_3D0_EN                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_3D0_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_RP_3D0_EN(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_3D0_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_RP_1D5_EN                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_1D5_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_RP_1D5_EN(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_1D5_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_RP_0D9_EN                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_0D9_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_RP_0D9_EN(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_RP_0D9_EN,x)
#define PERI1_GET_REG_RW_USBPHY_CC_REF_OPT                           PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_REF_OPT)
#define PERI1_SET_REG_RW_USBPHY_CC_REF_OPT(x)                        PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_REF_OPT,x)
#define PERI1_GET_REG_RW_USBPHY_U31_HOST_PHY                         PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_HOST_PHY)
#define PERI1_SET_REG_RW_USBPHY_U31_HOST_PHY(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_HOST_PHY,x)
#define PERI1_GET_REG_RW_USB_CC_DET_MODE                             PERI1_GET_REG32_BITS(PERI1_REG_RW_USB_CC_DET_MODE)
#define PERI1_SET_REG_RW_USB_CC_DET_MODE(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_USB_CC_DET_MODE,x)
#define PERI1_GET_REG_RW_USBPHY_CC_HOST_EN                           PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_HOST_EN)
#define PERI1_SET_REG_RW_USBPHY_CC_HOST_EN(x)                        PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_CC_HOST_EN,x)
#define PERI1_GET_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG                  PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG)
#define PERI1_SET_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG(x)               PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSTX_SEL_CONFIG,x)
#define PERI1_GET_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG                  PERI1_GET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG)
#define PERI1_SET_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG(x)               PERI1_SET_REG32_BITS(PERI1_REG_RW_USBPHY_U31_SSRX_SEL_CONFIG,x)
#define PERI1_GET_REG_RO_USBPHY_U31_SSTX_SEL                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_U31_SSTX_SEL)
#define PERI1_GET_REG_RO_USBPHY_U31_SSRX_SEL                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_U31_SSRX_SEL)
#define PERI1_GET_REG_RO_USBPHY_BIST_OK_U2                           PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_BIST_OK_U2)
#define PERI1_GET_REG_RO_USBPHY_BIST_OK_U3                           PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_BIST_OK_U3)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VOPEN_0                      PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_0)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VRD_0                        PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VRD_0)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VRA_0                        PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VRA_0)
#define PERI1_GET_REG_RO_USBPHY_CC_DEVICE_CONNECT_0                  PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_0)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_3D0_0                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_3D0_0)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_1D5_0                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_1D5_0)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_0D9_0                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_0D9_0)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VOPEN_1                      PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VOPEN_1)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VRD_1                        PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VRD_1)
#define PERI1_GET_REG_RO_USBPHY_CC_HOST_VRA_1                        PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_HOST_VRA_1)
#define PERI1_GET_REG_RO_USBPHY_CC_DEVICE_CONNECT_1                  PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_DEVICE_CONNECT_1)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_3D0_1                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_3D0_1)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_1D5_1                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_1D5_1)
#define PERI1_GET_REG_RO_USBPHY_CC_OUT_0D9_1                         PERI1_GET_REG32_BITS(PERI1_REG_RO_USBPHY_CC_OUT_0D9_1)
#define PERI1_GET_REG_RW_PKA_CFG_RW_MEM_MASK                         PERI1_GET_REG32_BITS(PERI1_REG_RW_PKA_CFG_RW_MEM_MASK)
#define PERI1_SET_REG_RW_PKA_CFG_RW_MEM_MASK(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_PKA_CFG_RW_MEM_MASK,x)
#define PERI1_GET_REG_RW_PKA_DPA_DISABLE                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PKA_DPA_DISABLE)
#define PERI1_SET_REG_RW_PKA_DPA_DISABLE(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PKA_DPA_DISABLE,x)
#define PERI1_GET_REG_RW_PKA_NOISE_SRC                               PERI1_GET_REG32_BITS(PERI1_REG_RW_PKA_NOISE_SRC)
#define PERI1_SET_REG_RW_PKA_NOISE_SRC(x)                            PERI1_SET_REG32_BITS(PERI1_REG_RW_PKA_NOISE_SRC,x)
#define PERI1_GET_REG_RW_PKA_NOISE_SRC_VALID                         PERI1_GET_REG32_BITS(PERI1_REG_RW_PKA_NOISE_SRC_VALID)
#define PERI1_SET_REG_RW_PKA_NOISE_SRC_VALID(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_PKA_NOISE_SRC_VALID,x)
#define PERI1_GET_REG_RW_PKA_CFG_CLK_EN                              PERI1_GET_REG32_BITS(PERI1_REG_RW_PKA_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PKA_CFG_CLK_EN(x)                           PERI1_SET_REG32_BITS(PERI1_REG_RW_PKA_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI0_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI0_CFG_CLK_EN)
#define PERI1_SET_REG_RW_SPI0_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI0_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI0_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI0_CLK_EN)
#define PERI1_SET_REG_RW_SPI0_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI0_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI1_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI1_CFG_CLK_EN)
#define PERI1_SET_REG_RW_SPI1_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI1_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI1_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI1_CLK_EN)
#define PERI1_SET_REG_RW_SPI1_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI1_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI2_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI2_CFG_CLK_EN)
#define PERI1_SET_REG_RW_SPI2_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI2_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI2_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI2_CLK_EN)
#define PERI1_SET_REG_RW_SPI2_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI2_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI_SLV_CFG_CLK_EN                          PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI_SLV_CFG_CLK_EN)
#define PERI1_SET_REG_RW_SPI_SLV_CFG_CLK_EN(x)                       PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI_SLV_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI_SLV_CLK_EN                              PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI_SLV_CLK_EN)
#define PERI1_SET_REG_RW_SPI_SLV_CLK_EN(x)                           PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI_SLV_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM1_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM1_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM1_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM1_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM1_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM1_CLK_EN)
#define PERI1_SET_REG_RW_PWM1_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM1_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM2_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM2_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM2_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM2_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM2_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM2_CLK_EN)
#define PERI1_SET_REG_RW_PWM2_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM2_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM3_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM3_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM3_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM3_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM3_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM3_CLK_EN)
#define PERI1_SET_REG_RW_PWM3_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM3_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM4_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM4_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM4_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM4_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM4_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM4_CLK_EN)
#define PERI1_SET_REG_RW_PWM4_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM4_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM5_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM5_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM5_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM5_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM5_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM5_CLK_EN)
#define PERI1_SET_REG_RW_PWM5_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM5_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM6_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM6_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM6_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM6_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM6_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM6_CLK_EN)
#define PERI1_SET_REG_RW_PWM6_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM6_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM7_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM7_CFG_CLK_EN)
#define PERI1_SET_REG_RW_PWM7_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM7_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_PWM7_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_PWM7_CLK_EN)
#define PERI1_SET_REG_RW_PWM7_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_PWM7_CLK_EN,x)
#define PERI1_GET_REG_RW_I2C5_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_I2C5_CFG_CLK_EN)
#define PERI1_SET_REG_RW_I2C5_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_I2C5_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_I2C5_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_I2C5_CLK_EN)
#define PERI1_SET_REG_RW_I2C5_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_I2C5_CLK_EN,x)
#define PERI1_GET_REG_RW_I2C6_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_I2C6_CFG_CLK_EN)
#define PERI1_SET_REG_RW_I2C6_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_I2C6_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_I2C6_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_I2C6_CLK_EN)
#define PERI1_SET_REG_RW_I2C6_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_I2C6_CLK_EN,x)
#define PERI1_GET_REG_RW_UART3_CFG_CLK_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART3_CFG_CLK_EN)
#define PERI1_SET_REG_RW_UART3_CFG_CLK_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART3_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_UART3_CLK_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_UART3_CLK_EN)
#define PERI1_SET_REG_RW_UART3_CLK_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_UART3_CLK_EN,x)
#define PERI1_GET_REG_RW_UART4_CFG_CLK_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART4_CFG_CLK_EN)
#define PERI1_SET_REG_RW_UART4_CFG_CLK_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART4_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_UART4_CLK_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_UART4_CLK_EN)
#define PERI1_SET_REG_RW_UART4_CLK_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_UART4_CLK_EN,x)
#define PERI1_GET_REG_RW_UART5_CFG_CLK_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART5_CFG_CLK_EN)
#define PERI1_SET_REG_RW_UART5_CFG_CLK_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART5_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_UART5_CLK_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_UART5_CLK_EN)
#define PERI1_SET_REG_RW_UART5_CLK_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_UART5_CLK_EN,x)
#define PERI1_GET_REG_RW_UART6_CFG_CLK_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART6_CFG_CLK_EN)
#define PERI1_SET_REG_RW_UART6_CFG_CLK_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART6_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_UART6_CLK_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_UART6_CLK_EN)
#define PERI1_SET_REG_RW_UART6_CLK_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_UART6_CLK_EN,x)
#define PERI1_GET_REG_RW_UART7_CFG_CLK_EN                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART7_CFG_CLK_EN)
#define PERI1_SET_REG_RW_UART7_CFG_CLK_EN(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART7_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_UART7_CLK_EN                                PERI1_GET_REG32_BITS(PERI1_REG_RW_UART7_CLK_EN)
#define PERI1_SET_REG_RW_UART7_CLK_EN(x)                             PERI1_SET_REG32_BITS(PERI1_REG_RW_UART7_CLK_EN,x)
#define PERI1_GET_REG_RW_I2S3_CFG_CLK_EN                             PERI1_GET_REG32_BITS(PERI1_REG_RW_I2S3_CFG_CLK_EN)
#define PERI1_SET_REG_RW_I2S3_CFG_CLK_EN(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_I2S3_CFG_CLK_EN,x)
#define PERI1_GET_REG_RW_I2S3_CLK_EN                                 PERI1_GET_REG32_BITS(PERI1_REG_RW_I2S3_CLK_EN)
#define PERI1_SET_REG_RW_I2S3_CLK_EN(x)                              PERI1_SET_REG32_BITS(PERI1_REG_RW_I2S3_CLK_EN,x)
#define PERI1_GET_REG_RW_SPI0_MST_DMA_HS_SEL                         PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI0_MST_DMA_HS_SEL)
#define PERI1_SET_REG_RW_SPI0_MST_DMA_HS_SEL(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI0_MST_DMA_HS_SEL,x)
#define PERI1_GET_REG_RW_SPI1_MST_DMA_HS_SEL                         PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI1_MST_DMA_HS_SEL)
#define PERI1_SET_REG_RW_SPI1_MST_DMA_HS_SEL(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI1_MST_DMA_HS_SEL,x)
#define PERI1_GET_REG_RW_SPI2_MST_DMA_HS_SEL                         PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI2_MST_DMA_HS_SEL)
#define PERI1_SET_REG_RW_SPI2_MST_DMA_HS_SEL(x)                      PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI2_MST_DMA_HS_SEL,x)
#define PERI1_GET_REG_RW_SPI_SLV_DMA_HS_SEL                          PERI1_GET_REG32_BITS(PERI1_REG_RW_SPI_SLV_DMA_HS_SEL)
#define PERI1_SET_REG_RW_SPI_SLV_DMA_HS_SEL(x)                       PERI1_SET_REG32_BITS(PERI1_REG_RW_SPI_SLV_DMA_HS_SEL,x)
#define PERI1_GET_REG_RW_UART3_DMA_HS_SEL                            PERI1_GET_REG32_BITS(PERI1_REG_RW_UART3_DMA_HS_SEL)
#define PERI1_SET_REG_RW_UART3_DMA_HS_SEL(x)                         PERI1_SET_REG32_BITS(PERI1_REG_RW_UART3_DMA_HS_SEL,x)
#define PERI1_GET_REG_RW_I2S3_DMA_HS_SEL                             PERI1_GET_REG32_BITS(PERI1_REG_RW_I2S3_DMA_HS_SEL)
#define PERI1_SET_REG_RW_I2S3_DMA_HS_SEL(x)                          PERI1_SET_REG32_BITS(PERI1_REG_RW_I2S3_DMA_HS_SEL,x)

////////////////////////////////////////////////////////////////
// reg group                                                  //
////////////////////////////////////////////////////////////////
#define PERI1_USBCTL_ADDR (PERI1_REGS_BASE+0x000)
#define PERI1_USBPHY_ADDR (PERI1_REGS_BASE+0x010)
#define PERI1_PKA_ADDR    (PERI1_REGS_BASE+0x088)
#define PERI1_SPI_ADDR    (PERI1_REGS_BASE+0x100)
#define PERI1_PWM_ADDR    (PERI1_REGS_BASE+0x110)
#define PERI1_UART_ADDR   (PERI1_REGS_BASE+0x134)
#define PERI1_EFUSE_ADDR  (PERI1_REGS_BASE+0x148)
#define PERI1_GMAC_ADDR   (PERI1_REGS_BASE+0x14c)
#define PERI1_SPACC_ADDR  (PERI1_REGS_BASE+0x150)
#define PERI1_USB_ADDR    (PERI1_REGS_BASE+0x154)
#define PERI1_I2S_ADDR    (PERI1_REGS_BASE+0x158)
#define PERI1_DMA_ADDR    (PERI1_REGS_BASE+0x200)
#define PERI1_MAC_ADDR    (PERI1_REGS_BASE+0x204)

typedef struct {
    // 0x000
    uint32_t reg_rw_usbctrl_hub_port_overcurrent            :  2;  //  1 :  0
    uint32_t reg_rw_usbctrl_hub_port_perm_attach            :  2;  //  3 :  2
    uint32_t reg_rw_usbctrl_host_num_u2_port                :  4;  //  7 :  4
    uint32_t reg_rw_usbctrl_host_num_u3_port                :  4;  // 11 :  8
    uint32_t reg_rw_usbctrl_host_u2_port_disable            :  1;  // 12 : 12
    uint32_t reg_rw_usbctrl_host_u3_port_disable            :  1;  // 13 : 13
    uint32_t _reserved0                                     :  2;  // 15 : 14
    uint32_t reg_rw_usbctrl_host_port_power_control_present :  1;  // 16 : 16
    uint32_t reg_rw_usbctrl_host_msi_enable                 :  1;  // 17 : 17
    uint32_t reg_rw_usbctrl_bus_filter_bypass               :  4;  // 21 : 18
    uint32_t reg_ro_usbctrl_pipe3_powerpresent              :  1;  // 22 : 22
    uint32_t reg_ro_usbctrl_utmiotg_vbusvalid               :  1;  // 23 : 23
    uint32_t reg_rw_usb_dbg_mode                            :  3;  // 26 : 24
    uint32_t reg_rw_usbctrl_utmisrp_bvalid                  :  1;  // 27 : 27
    uint32_t reg_rw_usbctrl_pipe3_powerpresent              :  1;  // 28 : 28
    uint32_t reg_rw_usbctrl_utmiotg_vbusvalid               :  1;  // 29 : 29
    uint32_t reg_rw_usbctrl_vbusdet_mode                    :  1;  // 30 : 30
    uint32_t reg_rw_usbctrl_pipe_datawidth                  :  1;  // 31 : 31
    // 0x004
    uint32_t reg_rw_usbctrl_startrxdetu3rxdet               :  1;  //  0 :  0
    uint32_t reg_rw_usbctrl_disrxdetu3rxdet                 :  1;  //  1 :  1
    uint32_t reg_ro_usbctrl_disrxdetu3rxdet_ack             :  1;  //  2 :  2
    uint32_t _reserved1                                     : 29;  // 31 :  3
    // 0x008
    uint32_t reg_ro_usbctrl_host_current_belt               : 12;  // 11 :  0
    uint32_t reg_ro_usbctrl_host_system_err                 :  1;  // 12 : 12
    uint32_t _reserved2                                     : 11;  // 23 : 13
    uint32_t reg_rw_usbctrl_xhc_bme                         :  1;  // 24 : 24
    uint32_t _reserved3                                     :  7;  // 31 : 25
    // 0x00c
    uint32_t reg_rw_usbctrl_fladj_30mhz_reg                 :  6;  //  5 :  0
    uint32_t reg_rw_usbctrl_pme_en                          :  1;  //  6 :  6
    uint32_t reg_ro_usbctrl_operational_mode                :  2;  //  8 :  7
    uint32_t reg_ro_usbctrl_clk_gate_ctrl                   :  2;  // 10 :  9
    uint32_t reg_ro_usbctrl_pme_generation                  :  1;  // 11 : 11
    uint32_t reg_ro_usbctrl_utmisrp_bvalid                  :  1;  // 12 : 12
    uint32_t _reserved4                                     : 19;  // 31 : 13
} peri1_usbctl;

typedef struct {
    // 0x010
    uint32_t reg_rw_usbphy_vcontrol            :  6;  //  5 :  0
    uint32_t reg_rw_usbphy_vcontrolloadm       :  1;  //  6 :  6
    uint32_t reg_rw_usbphy_lfpsrx_en           :  1;  //  7 :  7
    uint32_t reg_rw_usbphy_txbitstuffenalbe    :  1;  //  8 :  8
    uint32_t reg_rw_usbphy_txbitstuffenalbeh   :  1;  //  9 :  9
    uint32_t reg_rw_usbphy_xtlsel              :  3;  // 12 : 10
    uint32_t reg_rw_usbphy_pll_en              :  1;  // 13 : 13
    uint32_t reg_rw_usbphy_u31_ctle_off        :  1;  // 14 : 14
    uint32_t reg_rw_usbphy_u31_sscg_on         :  1;  // 15 : 15
    uint32_t reg_rw_usbphy_lpm_alive           :  1;  // 16 : 16
    uint32_t reg_rw_usbphy_hs_bist_mode        :  1;  // 17 : 17
    uint32_t reg_rw_usbphy_ls_en               :  1;  // 18 : 18
    uint32_t reg_rw_usbphy_debugsel            :  6;  // 24 : 19
    uint32_t reg_rw_usbphy_scan_chain_connect  :  1;  // 25 : 25
    uint32_t reg_rw_usbphy_internalloopback    :  1;  // 26 : 26
    uint32_t _reserved0                        :  1;  // 27 : 27
    uint32_t reg_rw_usbphy_cc_en               :  1;  // 28 : 28
    uint32_t _reserved1                        :  1;  // 29 : 29
    uint32_t reg_rw_usbphy_cc_lpf_opt          :  1;  // 30 : 30
    uint32_t reg_rw_usbphy_idpad_en            :  1;  // 31 : 31
    // 0x014
    uint32_t reg_rw_usbphy_cc_rd_en            :  1;  //  0 :  0
    uint32_t reg_rw_usbphy_cc_rp_3d0_en        :  1;  //  1 :  1
    uint32_t reg_rw_usbphy_cc_rp_1d5_en        :  1;  //  2 :  2
    uint32_t reg_rw_usbphy_cc_rp_0d9_en        :  1;  //  3 :  3
    uint32_t _reserved2                        :  2;  //  5 :  4
    uint32_t reg_rw_usbphy_cc_ref_opt          :  3;  //  8 :  6
    uint32_t _reserved3                        :  7;  // 15 :  9
    uint32_t reg_rw_usbphy_u31_host_phy        :  1;  // 16 : 16
    uint32_t reg_rw_usb_cc_det_mode            :  1;  // 17 : 17
    uint32_t reg_rw_usbphy_cc_host_en          :  1;  // 18 : 18
    uint32_t reg_rw_usbphy_u31_sstx_sel_config :  1;  // 19 : 19
    uint32_t reg_rw_usbphy_u31_ssrx_sel_config :  1;  // 20 : 20
    uint32_t reg_ro_usbphy_u31_sstx_sel        :  1;  // 21 : 21
    uint32_t reg_ro_usbphy_u31_ssrx_sel        :  1;  // 22 : 22
    uint32_t _reserved4                        :  9;  // 31 : 23
    // 0x018
    uint32_t reg_rw_usbphy_xcfgi0;
    // 0x01c
    uint32_t reg_rw_usbphy_xcfgi1;
    // 0x020
    uint32_t reg_rw_usbphy_xcfgi2;
    // 0x024
    uint32_t reg_rw_usbphy_xcfgi3;
    // 0x028
    uint32_t reg_rw_usbphy_xcfgi4;
    // 0x02c
    uint32_t reg_rw_usbphy_xcfgi5;
    // 0x030
    uint32_t reg_rw_usbphy_xcfgi6;
    // 0x034
    uint32_t reg_rw_usbphy_xcfgi7;
    // 0x038
    uint32_t reg_rw_usbphy_xcfgi8;
    // 0x03c
    uint32_t reg_rw_usbphy_xcfgi9;
    // 0x040
    uint32_t reg_rw_usbphy_xcfgi10;
    // 0x044
    uint32_t reg_rw_usbphy_xcfgi11;
    // 0x048
    uint32_t reg_rw_usbphy_xcfgi12;
    // 0x04c
    uint32_t reg_rw_usbphy_xcfgi13;
    // 0x050
    uint32_t reg_rw_usbphy_xcfgi14;
    // 0x054
    uint32_t reg_rw_usbphy_xcfgi15;
    // 0x058
    uint32_t reg_rw_usbphy_xcfgi16;
    // 0x05c
    uint32_t reg_rw_usbphy_xcfgi17;
    // 0x060
    uint32_t reg_rw_usbphy_xcfgi18;
    // 0x064
    uint32_t reg_rw_usbphy_xcfgi19;
    // 0x068
    uint32_t reg_rw_usbphy_xcfgi20;
    // 0x06c
    uint32_t reg_rw_usbphy_xcfgi21;
    // 0x070
    uint32_t reg_rw_usbphy_xcfgi22;
    // 0x074
    uint32_t reg_rw_usbphy_xcfgi23;
    // 0x078
    uint32_t reg_ro_usbphy_bist_ok_u2          :  1;  //  0 :  0
    uint32_t reg_ro_usbphy_bist_ok_u3          :  1;  //  1 :  1
    uint32_t _reserved5                        :  2;  //  3 :  2
    uint32_t reg_ro_usbphy_cc_host_vopen_0     :  1;  //  4 :  4
    uint32_t reg_ro_usbphy_cc_host_vrd_0       :  1;  //  5 :  5
    uint32_t reg_ro_usbphy_cc_host_vra_0       :  1;  //  6 :  6
    uint32_t reg_ro_usbphy_cc_device_connect_0 :  1;  //  7 :  7
    uint32_t reg_ro_usbphy_cc_out_3d0_0        :  1;  //  8 :  8
    uint32_t reg_ro_usbphy_cc_out_1d5_0        :  1;  //  9 :  9
    uint32_t reg_ro_usbphy_cc_out_0d9_0        :  1;  // 10 : 10
    uint32_t reg_ro_usbphy_cc_host_vopen_1     :  1;  // 11 : 11
    uint32_t reg_ro_usbphy_cc_host_vrd_1       :  1;  // 12 : 12
    uint32_t reg_ro_usbphy_cc_host_vra_1       :  1;  // 13 : 13
    uint32_t reg_ro_usbphy_cc_device_connect_1 :  1;  // 14 : 14
    uint32_t reg_ro_usbphy_cc_out_3d0_1        :  1;  // 15 : 15
    uint32_t reg_ro_usbphy_cc_out_1d5_1        :  1;  // 16 : 16
    uint32_t reg_ro_usbphy_cc_out_0d9_1        :  1;  // 17 : 17
    uint32_t _reserved6                        : 14;  // 31 : 18
    // 0x07c
    uint32_t reg_ro_usbphy_xcfgo0;
    // 0x080
    uint32_t reg_ro_usbphy_xcfgo1;
    // 0x084
    uint32_t reg_ro_usbphy_xcfgo2;
} peri1_usbphy;

typedef struct {
    // 0x088
    uint32_t reg_rw_pka_cfg_rw_mem_mask :  6;  //  5 :  0
    uint32_t reg_rw_pka_dpa_disable     :  1;  //  6 :  6
    uint32_t reg_rw_pka_noise_src       :  1;  //  7 :  7
    uint32_t reg_rw_pka_noise_src_valid :  1;  //  8 :  8
    uint32_t reg_rw_pka_cfg_clk_en      :  1;  //  9 :  9
    uint32_t _reserved0                 : 22;  // 31 : 10
} peri1_pka;

typedef struct {
    // 0x100
    uint32_t reg_rw_spi0_cfg_clk_en    :  1;  //  0 :  0
    uint32_t reg_rw_spi0_clk_en        :  1;  //  1 :  1
    uint32_t _reserved0                : 30;  // 31 :  2
    // 0x104
    uint32_t reg_rw_spi1_cfg_clk_en    :  1;  //  0 :  0
    uint32_t reg_rw_spi1_clk_en        :  1;  //  1 :  1
    uint32_t _reserved1                : 30;  // 31 :  2
    // 0x108
    uint32_t reg_rw_spi2_cfg_clk_en    :  1;  //  0 :  0
    uint32_t reg_rw_spi2_clk_en        :  1;  //  1 :  1
    uint32_t _reserved2                : 30;  // 31 :  2
    // 0x10c
    uint32_t reg_rw_spi_slv_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_spi_slv_clk_en     :  1;  //  1 :  1
    uint32_t _reserved3                : 30;  // 31 :  2
} peri1_spi;

typedef struct {
    // 0x110
    uint32_t reg_rw_pwm1_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm1_clk_en     :  1;  //  1 :  1
    uint32_t _reserved0             : 30;  // 31 :  2
    // 0x114
    uint32_t reg_rw_pwm2_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm2_clk_en     :  1;  //  1 :  1
    uint32_t _reserved1             : 30;  // 31 :  2
    // 0x118
    uint32_t reg_rw_pwm3_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm3_clk_en     :  1;  //  1 :  1
    uint32_t _reserved2             : 30;  // 31 :  2
    // 0x11c
    uint32_t reg_rw_pwm4_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm4_clk_en     :  1;  //  1 :  1
    uint32_t _reserved3             : 30;  // 31 :  2
    // 0x120
    uint32_t reg_rw_pwm5_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm5_clk_en     :  1;  //  1 :  1
    uint32_t _reserved4             : 30;  // 31 :  2
    // 0x124
    uint32_t reg_rw_pwm6_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm6_clk_en     :  1;  //  1 :  1
    uint32_t _reserved5             : 30;  // 31 :  2
    // 0x128
    uint32_t reg_rw_pwm7_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_pwm7_clk_en     :  1;  //  1 :  1
    uint32_t _reserved6             : 30;  // 31 :  2
    // 0x12c
    uint32_t reg_rw_i2c5_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_i2c5_clk_en     :  1;  //  1 :  1
    uint32_t _reserved7             : 30;  // 31 :  2
    // 0x130
    uint32_t reg_rw_i2c6_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_i2c6_clk_en     :  1;  //  1 :  1
    uint32_t _reserved8             : 30;  // 31 :  2
} peri1_pwm;

typedef struct {
    // 0x134
    uint32_t reg_rw_uart3_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_uart3_clk_en     :  1;  //  1 :  1
    uint32_t _reserved0              : 30;  // 31 :  2
    // 0x138
    uint32_t reg_rw_uart4_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_uart4_clk_en     :  1;  //  1 :  1
    uint32_t _reserved1              : 30;  // 31 :  2
    // 0x13c
    uint32_t reg_rw_uart5_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_uart5_clk_en     :  1;  //  1 :  1
    uint32_t _reserved2              : 30;  // 31 :  2
    // 0x140
    uint32_t reg_rw_uart6_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_uart6_clk_en     :  1;  //  1 :  1
    uint32_t _reserved3              : 30;  // 31 :  2
    // 0x144
    uint32_t reg_rw_uart7_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_uart7_clk_en     :  1;  //  1 :  1
    uint32_t _reserved4              : 30;  // 31 :  2
} peri1_uart;

typedef struct {
    // 0x148
    uint32_t reg_rw_efuse_cfg_clk_en;
} peri1_efuse;

typedef struct {
    // 0x14c
    uint32_t reg_rw_gmac_clk_en;
} peri1_gmac;

typedef struct {
    // 0x150
    uint32_t reg_rw_spacc_axi_clk_en;
} peri1_spacc;

typedef struct {
    // 0x154
    uint32_t reg_rw_usbctrl_clk_en;
} peri1_usb;

typedef struct {
    // 0x158
    uint32_t reg_rw_i2s3_cfg_clk_en :  1;  //  0 :  0
    uint32_t reg_rw_i2s3_clk_en     :  1;  //  1 :  1
    uint32_t _reserved0             : 30;  // 31 :  2
} peri1_i2s;

typedef struct {
    // 0x200
    uint32_t reg_rw_spi0_mst_dma_hs_sel :  2;  //  1 :  0
    uint32_t reg_rw_spi1_mst_dma_hs_sel :  2;  //  3 :  2
    uint32_t reg_rw_spi2_mst_dma_hs_sel :  2;  //  5 :  4
    uint32_t reg_rw_spi_slv_dma_hs_sel  :  2;  //  7 :  6
    uint32_t reg_rw_uart3_dma_hs_sel    :  2;  //  9 :  8
    uint32_t reg_rw_i2s3_dma_hs_sel     :  2;  // 11 : 10
    uint32_t _reserved0                 : 20;  // 31 : 12
} peri1_dma;

typedef struct {
    // 0x204
    uint32_t reg_rw_gmac_delay_count;
} peri1_mac;

#define PERI1_USBCTL ((volatile peri1_usbctl*)PERI1_USBCTL_ADDR)
#define PERI1_USBPHY ((volatile peri1_usbphy*)PERI1_USBPHY_ADDR)
#define PERI1_PKA    ((volatile peri1_pka*   )PERI1_PKA_ADDR   )
#define PERI1_SPI    ((volatile peri1_spi*   )PERI1_SPI_ADDR   )
#define PERI1_PWM    ((volatile peri1_pwm*   )PERI1_PWM_ADDR   )
#define PERI1_UART   ((volatile peri1_uart*  )PERI1_UART_ADDR  )
#define PERI1_EFUSE  ((volatile peri1_efuse* )PERI1_EFUSE_ADDR )
#define PERI1_GMAC   ((volatile peri1_gmac*  )PERI1_GMAC_ADDR  )
#define PERI1_SPACC  ((volatile peri1_spacc* )PERI1_SPACC_ADDR )
#define PERI1_USB    ((volatile peri1_usb*   )PERI1_USB_ADDR   )
#define PERI1_I2S    ((volatile peri1_i2s*   )PERI1_I2S_ADDR   )
#define PERI1_DMA    ((volatile peri1_dma*   )PERI1_DMA_ADDR   )
#define PERI1_MAC    ((volatile peri1_mac*   )PERI1_MAC_ADDR   )

#endif // __PERI1_REGS_H__

// vim:set ts=4 sw=4 et fenc=utf-8 fdm=marker:
