// Generated by gen_regs.tcl
// DO NOT EDIT THIS FILE

#ifndef __PMON0_REGS_H__
#define __PMON0_REGS_H__

#include <stdint.h>
//#include "chip_define.h"

#define PMON0_BASE 0x2B010000

////////////////////////////////////////////////////////////////
// baisc reg info                                             //
////////////////////////////////////////////////////////////////

#define PMON0_SOFT_RST_N_ADDR                   (PMON0_BASE+0x00)

#define PMON0_CFG_PERIOD_ADDR                   (PMON0_BASE+0x04)

#define PMON0_CFG_CHN_SEL_ADDR                  (PMON0_BASE+0x08)
#define PMON0_CFG_CHN_SEL_LSB                   0
#define PMON0_CFG_CHN_SEL_MASK                  0x00000007

#define PMON0_CFG_USE_ID_ADDR                   (PMON0_BASE+0x08)
#define PMON0_CFG_USE_ID_LSB                    8
#define PMON0_CFG_USE_ID_MASK                   0x00000100

#define PMON0_CFG_AXI_ID_ADDR                   (PMON0_BASE+0x08)
#define PMON0_CFG_AXI_ID_LSB                    16
#define PMON0_CFG_AXI_ID_MASK                   0xffff0000

#define PMON0_STS_WBYTES_ADDR                   (PMON0_BASE+0x0c)

#define PMON0_STS_RBYTES_ADDR                   (PMON0_BASE+0x10)

#define PMON0_STS_WREQ_NUM_ADDR                 (PMON0_BASE+0x1c)

#define PMON0_STS_WLAT_TOTAL_0_ADDR             (PMON0_BASE+0x20)
#define PMON0_STS_WLAT_TOTAL_1_ADDR             (PMON0_BASE+0x24)
#define PMON0_STS_WLAT_TOTAL_1_LSB              0
#define PMON0_STS_WLAT_TOTAL_1_MASK             0x0000ffff

#define PMON0_STS_WLAT_MAX_ADDR                 (PMON0_BASE+0x24)
#define PMON0_STS_WLAT_MAX_LSB                  16
#define PMON0_STS_WLAT_MAX_MASK                 0xffff0000

#define PMON0_STS_RREQ_NUM_ADDR                 (PMON0_BASE+0x28)

#define PMON0_STS_RLAT_TOTAL_0_ADDR             (PMON0_BASE+0x2c)
#define PMON0_STS_RLAT_TOTAL_1_ADDR             (PMON0_BASE+0x30)
#define PMON0_STS_RLAT_TOTAL_1_LSB              0
#define PMON0_STS_RLAT_TOTAL_1_MASK             0x0000ffff

#define PMON0_STS_RLAT_MAX_ADDR                 (PMON0_BASE+0x30)
#define PMON0_STS_RLAT_MAX_LSB                  16
#define PMON0_STS_RLAT_MAX_MASK                 0xffff0000

#define PMON0_STS_ERROR_ADDR                    (PMON0_BASE+0x34)

#define PMON0_INTR_EN_ADDR                      (PMON0_BASE+0x40)

#define PMON0_STS_INTR_ADDR                     (PMON0_BASE+0x44)

#define PMON0_CLR_INTR_ADDR                     (PMON0_BASE+0x44)

#define PMON0_DDR_REFRESH_IN_PROCESS_ADDR       (PMON0_BASE+0x50)
#define PMON0_DDR_REFRESH_IN_PROCESS_LSB        0
#define PMON0_DDR_REFRESH_IN_PROCESS_MASK       0x00000001

#define PMON0_DDR_Q_ALMOST_FULL_ADDR            (PMON0_BASE+0x50)
#define PMON0_DDR_Q_ALMOST_FULL_LSB             1
#define PMON0_DDR_Q_ALMOST_FULL_MASK            0x00000002

#define PMON0_DDR_DQS_OSC_IN_PROGRESS_ADDR      (PMON0_BASE+0x50)
#define PMON0_DDR_DQS_OSC_IN_PROGRESS_LSB       9
#define PMON0_DDR_DQS_OSC_IN_PROGRESS_MASK      0x00000200

#define PMON0_DDR_CTRL_DP_IDLE_ADDR             (PMON0_BASE+0x50)
#define PMON0_DDR_CTRL_DP_IDLE_LSB              10
#define PMON0_DDR_CTRL_DP_IDLE_MASK             0x00000400

#define PMON0_DDR_CONTROLLER_INIT_DONE_ADDR     (PMON0_BASE+0x50)
#define PMON0_DDR_CONTROLLER_INIT_DONE_LSB      11
#define PMON0_DDR_CONTROLLER_INIT_DONE_MASK     0x00000800

#define PMON0_DDR_CONTROLLER_BUSY_ADDR          (PMON0_BASE+0x50)
#define PMON0_DDR_CONTROLLER_BUSY_LSB           12
#define PMON0_DDR_CONTROLLER_BUSY_MASK          0x00001000

#define PMON0_DDR_CKE_STATUS_ADDR               (PMON0_BASE+0x50)
#define PMON0_DDR_CKE_STATUS_LSB                13
#define PMON0_DDR_CKE_STATUS_MASK               0x00006000

#define PMON0_DDR_DFI_ZQ_IN_PROGRESS_ADDR       (PMON0_BASE+0x50)
#define PMON0_DDR_DFI_ZQ_IN_PROGRESS_LSB        15
#define PMON0_DDR_DFI_ZQ_IN_PROGRESS_MASK       0x00008000

#define PMON0_DDR_PERF_MON_LP_CMDS_ADDR         (PMON0_BASE+0x50)
#define PMON0_DDR_PERF_MON_LP_CMDS_LSB          16
#define PMON0_DDR_PERF_MON_LP_CMDS_MASK         0x0fff0000

#define PMON0_CFG_DDR_PERF_CMD_SEL_ADDR         (PMON0_BASE+0x54)

#define PMON0_CFG_DDR_PERF_MON_SEL_ADDR         (PMON0_BASE+0x58)

#define PMON0_STS_DDR_PERF_MON_CNT_ADDR         (PMON0_BASE+0x5c)

#define PMON0_STS_DDR_PORT_CMD_FULL_CNT_ADDR    (PMON0_BASE+0x60)

#define PMON0_STS_DDR_PORT_RSP_FULL_CNT_ADDR    (PMON0_BASE+0x64)

#define PMON0_STS_DDR_PORT_WR_FULL_CNT_ADDR     (PMON0_BASE+0x68)

#define PMON0_STS_DDR_PORT_RD_FULL_CNT_ADDR     (PMON0_BASE+0x6c)

#define PMON0_DDR_WQOS0_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_WQOS0_LSB                     0
#define PMON0_DDR_WQOS0_MASK                    0x0000000f

#define PMON0_DDR_RQOS0_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_RQOS0_LSB                     4
#define PMON0_DDR_RQOS0_MASK                    0x000000f0

#define PMON0_DDR_WQOS1_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_WQOS1_LSB                     8
#define PMON0_DDR_WQOS1_MASK                    0x00000f00

#define PMON0_DDR_RQOS1_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_RQOS1_LSB                     12
#define PMON0_DDR_RQOS1_MASK                    0x0000f000

#define PMON0_DDR_WQOS2_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_WQOS2_LSB                     16
#define PMON0_DDR_WQOS2_MASK                    0x000f0000

#define PMON0_DDR_RQOS2_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_RQOS2_LSB                     20
#define PMON0_DDR_RQOS2_MASK                    0x00f00000

#define PMON0_DDR_WQOS3_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_WQOS3_LSB                     24
#define PMON0_DDR_WQOS3_MASK                    0x0f000000

#define PMON0_DDR_RQOS3_ADDR                    (PMON0_BASE+0x70)
#define PMON0_DDR_RQOS3_LSB                     28
#define PMON0_DDR_RQOS3_MASK                    0xf0000000

#define PMON0_DDR_WQOS4_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_WQOS4_LSB                     0
#define PMON0_DDR_WQOS4_MASK                    0x0000000f

#define PMON0_DDR_RQOS4_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_RQOS4_LSB                     4
#define PMON0_DDR_RQOS4_MASK                    0x000000f0

#define PMON0_DDR_WQOS5_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_WQOS5_LSB                     8
#define PMON0_DDR_WQOS5_MASK                    0x00000f00

#define PMON0_DDR_RQOS5_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_RQOS5_LSB                     12
#define PMON0_DDR_RQOS5_MASK                    0x0000f000

#define PMON0_DDR_WQOS6_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_WQOS6_LSB                     16
#define PMON0_DDR_WQOS6_MASK                    0x000f0000

#define PMON0_DDR_RQOS6_ADDR                    (PMON0_BASE+0x74)
#define PMON0_DDR_RQOS6_LSB                     20
#define PMON0_DDR_RQOS6_MASK                    0x00f00000

#define PMON0_DDR_WCOBUF_ADDR                   (PMON0_BASE+0x78)

#define PMON0_DDR_RAPCMD_ADDR                   (PMON0_BASE+0x7c)
#define PMON0_DDR_RAPCMD_LSB                    0
#define PMON0_DDR_RAPCMD_MASK                   0x0000007f

#define PMON0_DDR_WAPCMD_ADDR                   (PMON0_BASE+0x7c)
#define PMON0_DDR_WAPCMD_LSB                    8
#define PMON0_DDR_WAPCMD_MASK                   0x00007f00

////////////////////////////////////////////////////////////////
// reg access                                                 //
////////////////////////////////////////////////////////////////
#define PMON0_REG32(name)                       (*(volatile uint32_t*)name##_ADDR)

#define PMON0_GET_SOFT_RST_N                    PMON0_REG32(PMON0_SOFT_RST_N)
#define PMON0_SET_SOFT_RST_N(x)                 PMON0_REG32(PMON0_SOFT_RST_N) = (uint32_t)(x)
#define PMON0_GET_CFG_PERIOD                    PMON0_REG32(PMON0_CFG_PERIOD)
#define PMON0_SET_CFG_PERIOD(x)                 PMON0_REG32(PMON0_CFG_PERIOD) = (uint32_t)(x)
#define PMON0_GET_STS_WBYTES                    PMON0_REG32(PMON0_STS_WBYTES)
#define PMON0_GET_STS_RBYTES                    PMON0_REG32(PMON0_STS_RBYTES)
#define PMON0_GET_STS_WREQ_NUM                  PMON0_REG32(PMON0_STS_WREQ_NUM)
#define PMON0_GET_STS_WLAT_TOTAL_0              PMON0_REG32(PMON0_STS_WLAT_TOTAL_0)
#define PMON0_GET_STS_RREQ_NUM                  PMON0_REG32(PMON0_STS_RREQ_NUM)
#define PMON0_GET_STS_RLAT_TOTAL_0              PMON0_REG32(PMON0_STS_RLAT_TOTAL_0)
#define PMON0_GET_STS_ERROR                     PMON0_REG32(PMON0_STS_ERROR)
#define PMON0_GET_INTR_EN                       PMON0_REG32(PMON0_INTR_EN)
#define PMON0_SET_INTR_EN(x)                    PMON0_REG32(PMON0_INTR_EN) = (uint32_t)(x)
#define PMON0_GET_STS_INTR                      PMON0_REG32(PMON0_STS_INTR)
#define PMON0_SET_CLR_INTR(x)                   PMON0_REG32(PMON0_CLR_INTR) = (uint32_t)(x)
#define PMON0_GET_CFG_DDR_PERF_CMD_SEL          PMON0_REG32(PMON0_CFG_DDR_PERF_CMD_SEL)
#define PMON0_SET_CFG_DDR_PERF_CMD_SEL(x)       PMON0_REG32(PMON0_CFG_DDR_PERF_CMD_SEL) = (uint32_t)(x)
#define PMON0_GET_CFG_DDR_PERF_MON_SEL          PMON0_REG32(PMON0_CFG_DDR_PERF_MON_SEL)
#define PMON0_SET_CFG_DDR_PERF_MON_SEL(x)       PMON0_REG32(PMON0_CFG_DDR_PERF_MON_SEL) = (uint32_t)(x)
#define PMON0_GET_STS_DDR_PERF_MON_CNT          PMON0_REG32(PMON0_STS_DDR_PERF_MON_CNT)
#define PMON0_GET_STS_DDR_PORT_CMD_FULL_CNT     PMON0_REG32(PMON0_STS_DDR_PORT_CMD_FULL_CNT)
#define PMON0_GET_STS_DDR_PORT_RSP_FULL_CNT     PMON0_REG32(PMON0_STS_DDR_PORT_RSP_FULL_CNT)
#define PMON0_GET_STS_DDR_PORT_WR_FULL_CNT      PMON0_REG32(PMON0_STS_DDR_PORT_WR_FULL_CNT)
#define PMON0_GET_STS_DDR_PORT_RD_FULL_CNT      PMON0_REG32(PMON0_STS_DDR_PORT_RD_FULL_CNT)
#define PMON0_GET_DDR_WCOBUF                    PMON0_REG32(PMON0_DDR_WCOBUF)
#define PMON0_SET_DDR_WCOBUF(x)                 PMON0_REG32(PMON0_DDR_WCOBUF) = (uint32_t)(x)

////////////////////////////////////////////////////////////////
// reg bits access                                            //
////////////////////////////////////////////////////////////////
#define PMON0_GET_REG32_BITS(name)              ((PMON0_REG32(name) & name##_MASK) >> name##_LSB)
#define PMON0_SET_REG32_BITS(name,x)            do { \
    uint32_t val = PMON0_REG32(name); \
    val &= ~name##_MASK; \
    val |= ((x) << name##_LSB) & name##_MASK; \
    PMON0_REG32(name) = val; \
} while(0)

#define PMON0_GET_CFG_CHN_SEL                   PMON0_GET_REG32_BITS(PMON0_CFG_CHN_SEL)
#define PMON0_SET_CFG_CHN_SEL(x)                PMON0_SET_REG32_BITS(PMON0_CFG_CHN_SEL,x)
#define PMON0_GET_CFG_USE_ID                    PMON0_GET_REG32_BITS(PMON0_CFG_USE_ID)
#define PMON0_SET_CFG_USE_ID(x)                 PMON0_SET_REG32_BITS(PMON0_CFG_USE_ID,x)
#define PMON0_GET_CFG_AXI_ID                    PMON0_GET_REG32_BITS(PMON0_CFG_AXI_ID)
#define PMON0_SET_CFG_AXI_ID(x)                 PMON0_SET_REG32_BITS(PMON0_CFG_AXI_ID,x)
#define PMON0_GET_STS_WLAT_TOTAL_1              PMON0_GET_REG32_BITS(PMON0_STS_WLAT_TOTAL_1)
#define PMON0_GET_STS_WLAT_MAX                  PMON0_GET_REG32_BITS(PMON0_STS_WLAT_MAX)
#define PMON0_GET_STS_RLAT_TOTAL_1              PMON0_GET_REG32_BITS(PMON0_STS_RLAT_TOTAL_1)
#define PMON0_GET_STS_RLAT_MAX                  PMON0_GET_REG32_BITS(PMON0_STS_RLAT_MAX)
#define PMON0_GET_DDR_REFRESH_IN_PROCESS        PMON0_GET_REG32_BITS(PMON0_DDR_REFRESH_IN_PROCESS)
#define PMON0_GET_DDR_Q_ALMOST_FULL             PMON0_GET_REG32_BITS(PMON0_DDR_Q_ALMOST_FULL)
#define PMON0_GET_DDR_DQS_OSC_IN_PROGRESS       PMON0_GET_REG32_BITS(PMON0_DDR_DQS_OSC_IN_PROGRESS)
#define PMON0_GET_DDR_CTRL_DP_IDLE              PMON0_GET_REG32_BITS(PMON0_DDR_CTRL_DP_IDLE)
#define PMON0_GET_DDR_CONTROLLER_INIT_DONE      PMON0_GET_REG32_BITS(PMON0_DDR_CONTROLLER_INIT_DONE)
#define PMON0_GET_DDR_CONTROLLER_BUSY           PMON0_GET_REG32_BITS(PMON0_DDR_CONTROLLER_BUSY)
#define PMON0_GET_DDR_CKE_STATUS                PMON0_GET_REG32_BITS(PMON0_DDR_CKE_STATUS)
#define PMON0_GET_DDR_DFI_ZQ_IN_PROGRESS        PMON0_GET_REG32_BITS(PMON0_DDR_DFI_ZQ_IN_PROGRESS)
#define PMON0_GET_DDR_PERF_MON_LP_CMDS          PMON0_GET_REG32_BITS(PMON0_DDR_PERF_MON_LP_CMDS)
#define PMON0_GET_DDR_WQOS0                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS0)
#define PMON0_SET_DDR_WQOS0(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS0,x)
#define PMON0_GET_DDR_RQOS0                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS0)
#define PMON0_SET_DDR_RQOS0(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS0,x)
#define PMON0_GET_DDR_WQOS1                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS1)
#define PMON0_SET_DDR_WQOS1(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS1,x)
#define PMON0_GET_DDR_RQOS1                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS1)
#define PMON0_SET_DDR_RQOS1(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS1,x)
#define PMON0_GET_DDR_WQOS2                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS2)
#define PMON0_SET_DDR_WQOS2(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS2,x)
#define PMON0_GET_DDR_RQOS2                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS2)
#define PMON0_SET_DDR_RQOS2(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS2,x)
#define PMON0_GET_DDR_WQOS3                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS3)
#define PMON0_SET_DDR_WQOS3(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS3,x)
#define PMON0_GET_DDR_RQOS3                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS3)
#define PMON0_SET_DDR_RQOS3(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS3,x)
#define PMON0_GET_DDR_WQOS4                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS4)
#define PMON0_SET_DDR_WQOS4(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS4,x)
#define PMON0_GET_DDR_RQOS4                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS4)
#define PMON0_SET_DDR_RQOS4(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS4,x)
#define PMON0_GET_DDR_WQOS5                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS5)
#define PMON0_SET_DDR_WQOS5(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS5,x)
#define PMON0_GET_DDR_RQOS5                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS5)
#define PMON0_SET_DDR_RQOS5(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS5,x)
#define PMON0_GET_DDR_WQOS6                     PMON0_GET_REG32_BITS(PMON0_DDR_WQOS6)
#define PMON0_SET_DDR_WQOS6(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_WQOS6,x)
#define PMON0_GET_DDR_RQOS6                     PMON0_GET_REG32_BITS(PMON0_DDR_RQOS6)
#define PMON0_SET_DDR_RQOS6(x)                  PMON0_SET_REG32_BITS(PMON0_DDR_RQOS6,x)
#define PMON0_GET_DDR_RAPCMD                    PMON0_GET_REG32_BITS(PMON0_DDR_RAPCMD)
#define PMON0_SET_DDR_RAPCMD(x)                 PMON0_SET_REG32_BITS(PMON0_DDR_RAPCMD,x)
#define PMON0_GET_DDR_WAPCMD                    PMON0_GET_REG32_BITS(PMON0_DDR_WAPCMD)
#define PMON0_SET_DDR_WAPCMD(x)                 PMON0_SET_REG32_BITS(PMON0_DDR_WAPCMD,x)

////////////////////////////////////////////////////////////////
// reg group                                                  //
////////////////////////////////////////////////////////////////
#define PMON0_RESULT_ADDR        (PMON0_BASE+0x0c)
#define PMON0_DDR_STATUS_ADDR    (PMON0_BASE+0x50)
#define PMON0_DDR_PERF_STAT_ADDR (PMON0_BASE+0x5c)
#define PMON0_DDR_CFG_ADDR       (PMON0_BASE+0x70)


#endif // __PMON0_REGS_H__

// vim:set ts=4 sw=4 et fenc=utf-8 fdm=marker:
